export const dict = {
	es: {
		immo: {
			headerTitle: "Tu hogar ideal te espera",
			headerDescription:
				"Oportunidades únicas de vivienda en Luxemburgo, España y Dubái: ¡no las dejes escapar!",
			headerButton: "Buscar",
			sectionTitle_1: "Estrena tu nuevo espacio",
			sectionDescription_1:
				"Sé el primero en conocer las propiedades recién disponibles en el mercado.",
			sectionTitle_2: "Confort y seguridad para ti y tu familia",
			sectionDescription_2:
				"Disfruta de hogares acogedores y seguros para crear recuerdos inolvidables.",
			sectionTitle_3: "Emprende tu negocio ideal",
			sectionDescription_3:
				"Encuentra locales y oficinas perfectas para hacer crecer tu empresa, en ubicaciones estratégicas.",
			sectionTitle_4: "Listo para mudarse",
			sectionDescription_4:
				"Inmuebles con todo lo que necesitas para empezar a disfrutar de tu nuevo hogar desde el primer momento.",
			sectionTitle_5: "Espacio para toda la familia",
			sectionDescription_5:
				"Las más amplias propiedades con múltiples habitaciones y baños.",
			contactTitle: "Tu futuro comienza aquí",
			contactDescription:
				"Libling Immo es tu aliado perfecto para encontrar la propiedad de tus sueños.",
			contactFormTitle: "Déjanos tus datos y te contactaremos",
			contactFormButton: "Enviar",
			miniatureConector: "en",
			altConector: "en",
			backList: "Volver al listado",
			backSearch: "Volver al buscador",
			askFor: "Consultar",
			results: "resultados",
			page: "Página",
			luxemburg: "Propiedades en Luxemburgo",
			emirates: "Propiedades en Emiratos Árabes Unidos",
			spain: "Propiedades en España",
			earth: "Otros paises",
			success:"Éxito",
			successEmail:"Correo enviado exitosamente",
			failEmail:"Ha surgido un error en el envío del correo",
		},
		data: {
			"Individual": "Individual",
			"Collective": "Colectivo",
			"Natural gas": "Gas natural",
			"Diesel": "Gasóleo",
			"Propane": "Propano",
			"Wood": "Leña",
			"Pellet": "Pellet",
			"Biomass": "Biomasa",
			"Electricity": "Electricidad",
			"Solar thermal energy": "Energía solar térmica",
			"Air heat pump": "Bomba de calor",
			"Geothermal": "Geotermia",
			"Radiators": "Radiadores",
			"Underfloor heating": "Suelo radiante",
			"Convectors": "Convectores",
			"Thermal emitters": "Emisores térmicos",
			"Fireplaces": "Chimeneas",
			"Heat pumps": "Bombas de calor",
			"Air heat pump systems": "Sistemas de aerotermia",
			"Geothermal systems": "Sistemas de geotermia",
			"Solar thermal panels": "Paneles solares térmicos",
			"Pellet stoves": "Estufas de pellet",
			"Townhouse": "Adosado",
			"Apartment": "Apartamento",
			"House": "Casa",
			"Attic": "Ático",
			"Basement": "Sótano",
			"Duplex": "Dúplex",
			"Triplex": "Tríplex",
			"Commercial Premise": "Local comercial",
			"Office": "Oficina",
			"Terrain": "Terreno",
			"Investment": "Inversión inmobiliaria",
			"Rental management": "Gestión de alquiler",

		},
		adminProperties: {
			indexTitle: "Inmuebles registrados",
			indexEmptyListTitle: "Aún no has registrado tus inmuebles",
			indexEmptyListDescription:
				"Puedes registrar y gestionar tus inmuebles desde aquí.",
			createTitle: "Nueva propiedad",
			formLabelCountry: "Pais",
			formLabelCategory: "Categoría",
			formLabelCurrency: "Moneda",
			formLabelOptional: "Opcional",
			formLabelTitle: "Título",
			formLabelDescription: "Descripción",
			formLabelAddress: "Dirección",
			formLabelFurnished: "¿Está amoblado?",
			formLabelArea: "Área",
			formLabelBedrooms: "Número de dormitorios",
			formLabelBathrooms: "Número de baños",
			formLabelHeatingType: "Tipo de calefacción",
			formLabelHeatingMedium: "Medio de calefacción",
			formLabelHeatingEnergy: "Energía de calefacción",
			formLabelSale: "Venta",
			formLabelRent: "Alquiler",
			formLabelView: "Vista",
			formLabelPropertyType: "Tipo de propiedad",
			formLabelFrecuency: "Frecuencia de pago",
			formLabelPrice: "Precio",
			formLabelSufaces: "Superficies",
			formLabelBenefits: "Beneficios",
			formLabelNearPlaces: "Lugares cercanos",
			formLabelLegalNotes: "Noticias legales",
			formLabelTumbnail: "Portada",
			formLabelImages: "Imagenes",
			formLabelPhotos: "Sube fotos del inmueble",
			formLabelPhotosDescription:
				"Una vez cargadas, selecciona la imagen que quieras como portada.",
			formLabelPhotosAdvertise:
				"Las imágenes deben tener un peso menor a 2MB cada una.",
			formLabelMap: "Indica en el mapa la ubicación del inmueble",
			formLinkEdit: "Editar",
			formButtonPreview: "Vista previa",
			formButtonReturn: "Volver",
			formButtonRegister: "Registrar",
			formButtonBack: "Atrás",
			formButtonNext: "Siguiente",
			formButtonAddPhoto: "Agregar fotos",
			formButtonAddSurfaces: "Agregar superficie",
			formButtonAddBenefits: "Agregar beneficio",
			formButtonAddNearPlaces: "Agregar lugar cercano",
			formButtonAddLegalNotes: "Agregar nota legal",
			formOptionYes: "Sí",
			formOptionNo: "No",
			formOptionCancel: "Cancelar registro",
			formPlaceholderSelect: "Selecciona",
			formPlaceholderSelectText: "Selecciona o escribe...",
			formPlaceholderSelectAdd: "Agregar",
			formPlaceholderText: "Escribe aquí...",
			formPlaceholderView:
				"Ejemplo: panorámica, parcial, cerrada, vista al mar...",
			formPlaceholderSurfaces_1: "Cantidad",
			formPlaceholderSurfaces_2: "Descripción",
			formPlaceholderSurfaces_3: "Área",
			formPlaceholderBenefits: "Ejemplo: terraza, jardín, balcón...",
			formPlaceholderNearPlaces: "Ejemplo: supermercado, gimnasio, parque...",
			formPlaceholderLegalNotes:
				"Ejemplo: honorarios del propietario, consumo energético clase G...",
			formStepTitle_1: "Describe el inmueble",
			formStepTitle_2: "Detalla el espacio",
			formStepTitle_3: "Destaca las ventajas del inmueble",
			formStepTitle_4: "Agrega un título, descripción e imágenes",
			formStepTitle_5: "Establece las condiciones de pago",
			formPreviewTitle: "Revisa el inmueble antes de registrarto",
			formConfirmTitle: "Confirma la creación del nuevo inmueble",
			formConfirmOption: "Publicar inmueble",
			formStep: "Paso",
			formStepConnector: "de",
			formValidationRequired: "Este campo es requerido",
			formValidationCardDate: "Este campo debe tener el formato MM/YYYY. ej:12/2024",
			formValidationCvc: "Este campo debe tener 3 digitos",
			formValidationNumbers: "Este campo solo acepta números",
			formValidationLetters: "Este campo solo acepta letras",
			formValidationEmail: "Este campo debe ser un correo electrónico",
			formValidationPhotos: "Debe agregar como mínimo una imagen",
			previewSectionTitle_1: "Descripción del inmueble",
			previewSectionTitle_2: "Detalles del espacio",
			previewSectionTitle_3: "Ventajas del inmueble",
			previewSectionTitle_4: "Título, descripción e imágenes",
			previewSectionTitle_5: "Condiciones de pago",
			modalCreateTitle: "Confirma la creación del nuevo inmueble",
			modalCreateOption: "Publicar inmueble.",
			modalPublishConfirm: "Confirma la publicación del inmueble",
			modalPauseConfirm: "Confirma la pausa de la publicación",
			modalDeleteTitle: "Si eliminas el inmueble ya no podrás recuperarlo.",
			modalDeletePauseTitle:
				"Si eliminas el inmueble ya no podrás recuperarlo.",
			modalDeleteText:
				"Puedes pausar la publicación para conservarlo y reactivarla más tarde.",
			modalDeleteButton: "Eliminar",
			toastDelete: "El inmueble fue eliminado con éxito.",
			toastPublish: "El inmueble fue publicado con éxito.",
			toastPause: "La publicación fue pausada con éxito.",
			actionPublish: "Publicar",
			actionPause: "Pausar",
			actionDetail: "Ver detalle",
			actionPreview: "Vista previa",
			tabAll: "Todos",
			listBasic: "Básico",
			listStatus: "Estado",
			listActions: "Acciones",
			listActive: "Activo",
			listInactive: "Inactivo",
			linesPerPage: "Líneas por página",
			selecteds: "seleccionados",
			activePub: "Publicación activa",
			inactivePub: "Publicación pausada",
		},
		adminAffiliate: {
			indexTitle: "Afiliados",
			indexEmptyListTitle: "Aún no se han registrado afiliados",
			indexSearchPlaceholder: "Buscar afiliados",
			tabAll: "Todos",
			listName: "Nombre",
			listPhone: "Teléfono",
			listEmail: "Correo electrónico",
			listLastPay: "Último pago",
			listStatus: "Estado",
			listActions: "Acciones",
			listActive: "Al dia",
			listInactive: "En mora",
			linesPerPage: "Líneas por página",
			selecteds: "seleccionados",
			detailTitle : "Renovaciones de ",
			detailColumn1 : "Número de transacción",
			detailColumn2 : "Fecha",
			detailColumn3 : "Plan de afiliación",
			detailAction : "Cerrar",
			formStepConnector: "de",

		},
		adminNav: {
			propertiesTitle: "Inmuebles",
			affiliateTitle: "Afiliaciones",
			dashboardTitle: "Inicio",
			closeSession: "Cerrar sesión",
		},
		auth: {
			login_title: "Vamos a ingresar a tu cuenta",
			login_subtitle: "Por favor, ingresa tus datos",
			change_password_title: "Cambiar contraseña",
			change_password_subtitle:
				"A continuación, ingresa tu nueva contraseña para restablecerla",
			login_email: "Correo electrónico",
			login_password: "Contraseña",
			login_password_confirm: "Repetir contraseña",
			login_forgot: "¿Olvidaste tu contraseña?",
			login_button: "Iniciar sesión",
			login_remember: "Recuérdame",
			login_placeholder: "Escribe aqui...",
			login_email_required: "El correo es requerido",
			login_password_required: "La contraseña es requerida",
			login_password_confirmation_required: "Las contraseñas no coninciden",
			forgot_password_title: "Recuperar contraseña",
			forgot_password_subtitle:
				"Ingresa el correo electrónico que usaste al registrarte. Recibirás un enlace para restablecer tu contraseña.",
			email_not_found_title: "Correo electrónico no registrado",
			email_not_found_subtitle:
				"Parece que no encontramos una cuenta asociada a tu correo electrónico. Asegúrate de haber introducido la dirección correcta y vuelve a intentarlo.",
			email_send_title: "Correo electrónico enviado",
			email_send_subtitle:
				"Ingresa al enlace enviado a tu correo electrónico para restablecer tu contraseña.",
			email_send_required: "El correo electrónico es requerido",
			email_send_validation: "El campo debe ser un correo electrónico",
			email_set_title: "Contraseña restablecida",
			email_set_subtitle: "Ahora puedes continuar a tu entorno de trabajo.",
			formButtonContinue: "Continuar",
			formButtonSendLink: "Enviar enlace",
			formButtonReturn: "Volver",
			formButtonChangePassword: "Cambiar contraseña",
			formButtonOrLogin: "O inicia sesión",
			error_credentials: "Las credenciales no son correctas",
			error_default: "Ha ocurrido un error",
		},
		navbar: {
			link_1: "Quienes somos",
			link_2: "Inicio",
			link_3: "Servicios",
			link_4: "Contáctanos",
			link_5: "Afiliación",
			link_6: "Afiliarme",
			link_7: "Renovar mi afiliación",
			admin_1: "Propiedades",
		},
		footer: {
			title_1: "Contáctanos",
			title_2: "Deja tu correo y te contactaremos",
			title_3: "Síguenos",
			rights: "Todos los derechos reservados",
			privacy: "Políticas de privacidad",
			cookies: "Política de cookies",
			terms: "Términos de uso",
		},
		home: {
			miniTitleHeader1:"Programa de afiliados",
			miniTitleHeader2:"Programa de afiliados",
			miniTitleHeader3:"Orientación personalizada",
			bigTitleHeader1_1:"INICIEMOS ",
			bigTitleHeader1_2:"el viaje juntos",
			bigTitleHeader2_1:"Ahorra ",
			bigTitleHeader2_2:"hasta un 50%",
			bigTitleHeader3_1:"Potencia ",
			bigTitleHeader3_2:"tu mudanza",
			commonHeader1:"Con nuestro programa de afiliados participas en increíbles promociones para comenzar tu nueva vida en Luxemburgo.",
			commonHeader2:"y haz que tu mudanza a Luxemburgo sea más asequible con nuestro programa de afiliados.",
			commonHeader3:"Recibe asesoramiento y soporte personalizados de nuestros expertos en reubicación a través de videollamadas.",
			actionButtonHeader1:"Descubre cómo",
			actionButtonHeader2:"Descubre cómo",
			actionButtonHeader3:"Descubre cómo",
			sectionPartners:"Estas empresas ya confían en nosotros",
			sectionButton_1: "Quiero agendar una cita",
			sectionButton_2: "Quiero saber más",
			titleHeader_1: "Con Libling solutions su",
			titleHeader_2: "instalación en Luxemburgo",
			titleHeader_3: "es fácil y segura.",
			subtitleHeader_1: "",
			subtitleHeader_2: "",
			sectionMiniTitle_1: "Ayuda personalizada",
			sectionMiniTitle_2: "Conoce nuestros planes",
			sectionMiniTitle_3: "Asesoramiento completo",
			sectionTitle_1: "Estamos a su lado para ayudarle en todo lo que necesite",
			sectionContent_1:
				"Brindándole un servicio completo y apoyo óptimo en su proceso de instalación en Luxemburgo 🇱🇺",
			sectionTitle_2: "Juntos podremos lograrlo",
			sectionContent_2:
				"Empezar en un país distinto a veces puede ser retador, pero no se preocupe estamos con usted para facilitarle los procesos administrativos y pueda integrarse rápidamente en la comunidad luxemburguesa.",
			sectionTitle_3: "Nuestros servicios",
			sectionList_3: [
				"Visitar o instalarse en el gran ducado",
				"Búsqueda de un bien inmobiliario",
				"Asesoramiento personalizado",
				"Tours y puntos de interes",
			],
			sectionTitle_4: "Le ayudamos a gestionar y le asesoramos",
			sectionList_4: [
				"Solicitud de permiso de trabajo/autorización temporal.",
				"Búsqueda de su casa, apartamento.",
				"Busqueda de escuela y guardería para sus hijos.",
				"Mercado inmobiliario, servicio de compra-venta, alquiler y gestión de propiedades.",
				"Asesoramiento de bienes inmuebles.",
				"Organización de la mudanza.",
			],
			reviewName_1: "MARIA SMITH",
			reviewDescription_1:
				"Hace 1 mes que vivo en Luxemburgo gracias a Libling. Pude encontrar un trabajo en el sector de tecnología, que es donde mejor me especializo. También me ayudaron sobre cómo abrir una cuenta bancaria, solicitud de permiso de residencia y como hacer amigos en Luxemburgo.",
			reviewName_2: "LUIS MORENO",
			reviewDescription_2:
				"Mi  nombre es Luis Moreno y soy de Peru. Mi novia y yo decidimos irnos a Luxemburgo buscando un mejor futuro para ambos hace un año, solicitamos la ayuda de Libling y definitivamente una de las mejores decisiones que pudimos tomar.",
			reviewName_3: "LAURA MARTINEZ",
			reviewDescription_3:
				"Hola, soy Laura de Mexico. Luxemburgo para mí siempre ha sido una ciudad magnífica y con grandes oportunidades, así que contacté a Libling para tener los requisitos necesarios para poder vivir allí. Los recomiendo al 100%",
		},
		services: {
			bigTitleHeader1_1:"Mudarse a Luxemburgo nunca fue tan fácil",
			commonHeader1:"Asegura tu mudanza a Luxemburgo con la orientación profesional de ",
			commonHeader2:"Libling Solutions",
			commonHeader3:" a tu disposición.",
			sectionTitle_1: "Afiliaciones",
			sectionSubtitle_1: "Prueba ahora nuestras afiliaciones",
			sectionContent_1_1: "Elige el plan ",
			sectionContent_1_2: "que mejor se adapte a tus necesidades y presupuesto:",
			sectionOption1: "1 mes",
			sectionOption2: "6 meses",
			sectionOption3: "1 año",
			sectionOptionBy1: "mes",
			sectionOptionBy2: "semestre",
			sectionOptionBy3: "año",
			planActionButton:"Solicitar",
			planTitle1:"Estudiante",
			planContent1:"Estudiar en Luxemburgo.",
			planList1: ["Actualizaciones", "Eventos y oportunidades futuras para estudiantes internacionales", "Consejos sobre cómo postularse y dónde instalarse", "Acceso exclusivo a infomacion sobre universidades, progamas, becas y opciones de alojamiento para estudiantes", "Sesión de preguntas y respuestas"],
			planList1Extra: ["Actualizaciones", "Eventos y oportunidades futuras para estudiantes internacionales", "Consejos sobre cómo postularse y dónde instalarse", "Acompañamiento continuo durante todo su proceso de adaptación", "Tramitación completa de documentos y autorizaciones", "⁠Búsqueda de alojamiento y acompañamiento en el proceso de mudanza", "2 días de asistencia personalizada"],
			planTitle2: "Demandante de empleo",
			planContent2: "Instalarse en Luxemburgo",
			planList2: ["Acceso exclusivo a guías para encontrar trabajo y solicitar visas y navegar el proceso de reubicación", "Recursos seleccionados sobre empresas, costo de vivir y vida en Luxemburgo", "Suscripción a seminarios web con la industria de expertos en estrategias de búsqueda de empleo"],
			planList2Extra: ["Acceso exclusivo a guías para encontrar trabajo y solicitar visas y navegar el proceso de reubicación", "Recursos seleccionados sobre empresas, costo de vivir y vida en Luxemburgo", "Suscripción a seminarios web con la industria de expertos en estrategias de búsqueda de empleo", "2 días de asistencia personalizada"],
			planTitle3: "Emprendedor",
			planContent3: "Crear una empresa en Luxemburgo",
			planList3: ["Orientación integral sobre negocios, configuración, requisitos legales y licencias", "Acceso a consultas en línea sobre temas como financiación, marketing y formación de un equipo en Luxemburgo", "Retos para afrontar la puesta en marcha del negocio en Luxemburgo"],
			planList3Extra: ["Orientación integral sobre negocios, configuración, requisitos legales y licencias", "Acceso a consultas en línea sobre temas como financiación, marketing y formación de un equipo en Luxemburgo", "Retos para afrontar la puesta en marcha del negocio en Luxemburgo", "Requisitos y documentos necesarios para la solicitud de visado de empresario/inversor", "2 días de asistencia personalizada"],
			sectionSubtitle_2: "Beneficios de pertenecer a nuestros afiliados",
			sectionList_2: ["Descuentos en servicios y paquetes","Sesiones de llamadas personalizadas","Orientación personalizada","Video llamadas para aclarar dudas","Hasta 50% de descuento en tu segundo paquete de servicios","Actualización constante","Acceso a programas, talleres e información exclusiva"],
			sectionTitle_3: "Nuestros paquetes",
			sectionSubtitle_3: "Tu camino hacia una nueva vida en Luxemburgo",
			sectionContent_3: "Elige el plan que mejor se adapte a tus necesidades y presupuesto:",
			packageTitle1:"Básico",
			packageList1:["Asistencia inicial para tu llegada.","Gestión de trámites administrativos esenciales.","Inscripción en servicios básicos (electricidad, agua, internet)."],
			packageTitle2:"Premium",
			packageList2:["Asistencia integral en todos los aspectos de tu nueva vida.","Gestión completa de trámites administrativos y legales.", "Búsqueda de vivienda y acompañamiento personalizado en la mudanza.", "Orientación para la elección del colegio ideal para tus hijos.", "Alojamiento temporal en un entorno confortable.", "Recepción y traslado desde el aeropuerto.", "Tour de orientación de 3 días con asistencia personalizada."],
			packageTitle3:"Estándar",
			packageList3:["Asistencia continua durante tu proceso de adaptación.","Tramitación completa de documentos y permisos.", "Búsqueda de vivienda y acompañamiento en el proceso de mudanza.", "Orientación para la elección del colegio ideal para tus hijos.","2 días de asistencia personalizada."],
			sectionTitle_4: "Consultorías adicionales",
			sectionSubtitle_4: "Más que una empresa, somos un equipo a tu servicio",
			sectionContent_4: "En Libling contamos con un equipo de expertos en diversas áreas para ofrecerte un apoyo integral.",
			aditionalConsultTitle_1:"Consultoría inmobiliaria",
			aditionalConsultContent_1:"Nuestro equipo de expertos te brindará asesoría personalizada para que tomes la mejor decisión para ti y tu familia.",
			aditionalConsultTitle_2:"Asesoría en arquitectura, construcción e inversión",
			aditionalConsultContent_2:"Te brindamos asesoría en inversiones inmobiliarias, para que puedas obtener el máximo rendimiento de tu capital.",
			aditionalConsultTitle_3:"Orientación jurídica y legal",
			aditionalConsultContent_3:"Te ofrecemos asesoría legal integral para que te sientas seguro y protegido en Luxemburgo.",
			aditionalConsultTitle_4:"Consultorías médicas",
			aditionalConsultContent_4:"Tu salud es lo más importante. Por ello te guiamos en el proceso de dar con el especialista adecuado.",
			aditionalConsultTitle_5:"Integración a la vida social y cultural del país",
			aditionalConsultContent_5:"Te notificaremos de actividades y eventos para que puedas disfrutar al máximo de tu nueva vida.",
			aditionalConsultTitle_6:"Atención personalizada en tu viaje y mudanza",
			aditionalConsultContent_6:"¡Nos encargaremos de los detalles! Desde la planificación del viaje hasta la instalación en tu nuevo hogar.",
			sectionTitle_5: "aún hay más",
			sectionSubtitle_5: "Servicios adicionales para tu comodidad",
			aditionalService_1:"Recepción y traslado desde el aeropuerto.",
			aditionalService_2:"Planificación de tu viaje y mudanza.",
			aditionalService_3:"Asistencia en servicios de limpieza y mantenimiento.",
			contactTitle:"Da ahora el primer paso hacia tu nueva vida",
			contactActionButton:"Agendar una cita",
			formPageLabel_1:"Datos personales",
			formPageLabel_2:"Detalles de pago",
			formTitle_1:"Datos básicos",
			formTitle_2:"Indícanos tu correo electrónico",
			modalTitle:"Plan seleccionado",
			inputLabel_1:"Nombre",
			inputPlaceholder_1:"Escribe tu nombre",
			inputLabel_2:"Teléfono",
			inputPlaceholder_2:"Escribe tu teléfono",
			inputLabel_3:"Correo electrónico",
			inputPlaceholder_3:"Correo electrónico",
			inputLabel_4:"País",
			inputPlaceholder_4:"Selecciona tu país",
			inputLabel_5:"Observación",
			inputPlaceholder_5:"Escribe aquí...",
			inputLabel_6:"Número de tarjeta",
			inputPlaceholder_6:"Ingresa tu número de tarjeta",
			inputLabel_7:"Nombre",
			inputPlaceholder_7:"Escribe tu nombre",
			inputLabel_8:"Expira",
			inputPlaceholder_8:"Fecha de expiración",
			inputLabel_9:"CVC",
			inputPlaceholder_9:"Ingresa el código CVC",
			inputLabel_10:"País",
			inputPlaceholder_10:"Selecciona tu país",
			inputLabel_11:"Provincia",
			inputPlaceholder_11:"Selecciona",
			inputLabel_12:"Código postal",
			inputPlaceholder_12:"Ingresa el código postal",
			buttonAction_1:"Salir",
			buttonAction_2:"Siguiente paso",
			buttonAction_3:"Atrás",
			buttonAction_4:"Afiliarme",
			buttonAction_5:"Elegir un plan distinto",
			priceLabel:"Subtotal",
			successMessageTitle:"Su afiliación fue efectuada con éxito.",
			successMessageContent:"Por favor, revise su correo electrónico.",
			errorMessageTitle:"Su afiliación no pudo ser efectuada.",
			errorMessageContent:"No se pudo comprobar la información de su pago.",
			infoMessageTitle:"Estamos verificando tu pago.",
			infoMessageContent:"No salgas de esta página, mientras verificamos tu pago.",
			errorFindAffiliate: "Este correo no se encuentra afiliado",
			priceTotalLabel:"Total",
			feeLabel:"Impuesto",
			planDate:"Fecha de corte",
			plan:"Plan",
		},
		contact: {
			miniTitleHeader1:"Embárcate en la aventura",
			bigTitleHeader1:"¡Agenda una cita ahora!",
			formTitle1:"Elige un día para poder contactarte",
			formTitle2:"Coméntanos un poco de ti",
			formLabelName:"Nombres",
			formPlaceholderName:"Dinos tu nombre y apellido",
			formLabelSubject:"Asunto a tratar",
			formPlaceholderSubject:"Selecciona",
			formLabelEmail:"Correo electrónico",
			formPlaceholderEmail:"Ej.: example@email.com",
			formLabelMessage:"Mensaje",
			formPlaceholderMessage:"Dinos el motivo por el que nos contactas",
			formActionButton:"Agendar cita",
			formSubjectList:[
				{
					key:'job',
					value:'Quiero trabajar en Luxemburgo',
				},
				{
					key:'jobs',
					value:'Quiero saber acerca de empleos en Luxemburgo',
				},
				{
					key:'job_permit',
					value:'Quiero ⁠información sobre permiso de trabajo',
				},
				{
					key:'business',
					value:'Quiero ⁠iniciar un negocio en Luxemburgo',
				},
				{
					key:'study',
					value:'Quiero ⁠estudiar en Luxemburgo',
				},
				{
					key:'languages',
					value:'Quiero ⁠aprender de idiomas en Luxemburgo',
				},
				{
					key:'stay',
					value:'Quiero saber donde alojarme en Luxemburgo',
				},
				{
					key:'investment',
					value:'Quiero ⁠⁠invertir en Luxemburgo',
				},
			],

			calendarTitle: "Selecciona una fecha",
			sectionTitle_1: "¡Agende con nosotros!",
			sectionContent_1:
				"Desea tener una reunión con Libling solutions. Estamos a su entera disposición, para darle un servicio integral.",
			sectionTitle_2: "Le mantendremos siempre al corriente de todo",
			sectionContent_2:
				"Porque usted es nuestra prioridad. Inscríbase a nuestro boletín informativo para que sea el primero en recibir todas nuestras novedades, noticias, productos y servicios.",
			form_name: "Nombres",
			form_subject: "Asunto",
			form_email: "Correo electrónico",
			form_message: "Mensaje",
			form_button: "Enviar",
		},
		about: {
			headerTitle_1: "¡Embárcate en la aventura!",
			headerSubtitle_1: "¿Anhelas un nuevo comienzo en el corazón de Europa?",
			headerContent_1_1: "Libling Solutions",
			headerContent_1_2: " te acompaña en cada paso hacia un futuro brillante en ",
			headerContent_1_3: "Luxemburgo.",
			actionButton_1:"Entérate de lo que Libling te ofrece",
			sectionTitle_1: "Conócenos",
			sectionSubtitle_1: "¿Quiénes somos?",
			sectionContent_1_1: "Libling Solutions",
			sectionContent_1_2: " está dedicada a transformar su reubicación a ",
			sectionContent_1_3: " Luxemburgo ",
			sectionContent_1_4: " en una experiencia positiva. Nuestro equipo multilingüe ofrece orientación experta y soporte personalizado, encargándose de todo, desde la búsqueda de vivienda hasta los trámites de inmigración. Priorizamos la comunicación clara y su bienestar, asegurando una mudanza fluida y sin estrés. Permítanos ayudarlo a convertir a Luxemburgo en su hogar con facilidad y confianza.",
			actionButton_1_1:"Saber más",
			sectionTitle_2: "Profesionalidad",
			sectionSubtitle_2: "Innovadores en Reubicación y Bienes Raíces en el Gran Ducado",
			sectionContent_2_1: "En ",
			sectionContent_2_2: "Libling Solutions",
			sectionContent_2_3: ", ofrecemos servicios integrales para satisfacer todas sus necesidades de reubicación y bienes raíces. Creemos que mudarse a una nueva casa debe ser una experiencia placentera y personalizada, garantizando que usted y su familia disfruten de una transición fluida. Confíe en nosotros para brindarle excelencia en cada paso de su proceso de reubicación.",
			actionButton_2:"Saber más",
			sectionTitle_3: "Servicio de excelencia",
			sectionSubtitle_3: "Nuestro objetivo es tu bienestar",
			sectionContent_3_1: "Libling Solutions",
			sectionContent_3_2: " tiene como objetivo apoyarte, ayudarte y facilitarte todo para que tu mudanza al Gran Ducado sea placentera y cómoda. Contamos con un equipo de profesionales especializados en cada una de tus necesidades y en tu idioma. Nuestra prioridad es brindarte un servicio de calidad.",
			actionButton_3:"Saber más",
			sectionTitle_4: "Contáctanos",
			sectionSubtitle_4_1: "Comienza tu viaje a Luxemburgo con ",
			sectionSubtitle_4_2: "Libling Solutions",
			sectionContent_4: "Contacta a nuestro equipo hoy mismo y descubre cómo podemos ayudarte a crear un nuevo hogar.",
			actionButton_4:"Quiero agendar una cita",
		},
		mail: {
			main: "Quiero obtener más información acerca de libling",
			subject_1: "Información",
			subject_2: "Servicios",
			subject_3: "Saludos",
			package: "Estoy interesado en el siguiente paquete: ",
			date: "Hola quisiera una cita para el día: ",
			notify: "Su mensaje ha sido enviado con éxito",
			failed: "No se ha podido completar la solicitud",

			infoContent1:"Hola",
			infoContent2:". Agradecemos tu mensaje. Estamos revisando tu solicitud y te daremos una respuesta pronto.",
			affiliateTitle:"Gracias por unirte a nuestra familia",
			affiliateTitleAdmin:"Se ha registrado un nuevo pago de afiliado",
			affiliateContent_1:"¡Te damos la bienvenida!",
			affiliateContent_2:"En Libling estamos muy contentos de que te hayas unido a nuestro programa de afiliados.",
			affiliateContent_3:"Tu decisión de formar parte de nuestra comunidad nos llena de alegría y nos impulsa a seguir ofreciendo el mejor servicio a quienes buscan un nuevo comienzo en Luxemburgo.",
			affiliateContent_4:"Como afiliado/a, tienes acceso a beneficios exclusivos y al apoyo constante de nuestro equipo de expertos.",
			affiliateContent_5:"¡Juntos podemos lograr grandes cosas y ayudar a muchos a cumplir sus sueños!",
			contentBottom:"El equipo de Libling.",

			footerTopTitle:"Estamos para servirte",
			footerTopText_1:"¿Tienes preguntas?",
			footerTopText_2:" Escríbenos a ",
			footerTopText_3:"info@libling.com",
			footerTopText_4:" y estaremos en contacto contigo lo más pronto posible. También nos puedes dejar comentarios acerca de nuestros servicios en ",
			footerTopText_5:"info@libling.lu",
			footerBottomText_1:"Término",
			footerBottomText_2:"Privacidad",
			footerBottomText_3:"Contáctanos",
			footerBottomText_4:"Dar de baja",
		},
	},
	en: {
		immo: {
			headerTitle: "Your dream home awaits",
			headerDescription:
				"Unique housing opportunities in Luxembourg, Spain and Dubai: don't miss out!",
			headerButton: "Search",

			sectionTitle_1: "Discover your new space",
			sectionDescription_1:
				"Be the first to know about newly available properties on the market.",
			sectionTitle_2: "Comfort and security for you and your family",
			sectionDescription_2:
				"Enjoy cozy and safe homes to create unforgettable memories.",
			sectionTitle_3: "Start your ideal business",
			sectionDescription_3:
				"Find perfect commercial and office spaces to grow your business, in strategic locations.",
			sectionTitle_4: "Move-in ready",
			sectionDescription_4:
				"Properties with everything you need to start enjoying your new home from the first moment.",
			sectionTitle_5: "Space for the whole family",
			sectionDescription_5:
				"The most spacious properties with multiple bedrooms and bathrooms.",
			contactTitle: "Your future starts here",
			contactDescription:
				"Libling Immo is your perfect ally to find the property of your dreams.",
			contactFormTitle: "Leave us your details and we will contact you",
			contactFormButton: "Send",
			miniatureConector: "for",
			altConector: "in",
			backList: "Back to list",
			backSearch: "Back to search",
			askFor: "Consult",
			results: "results",
			page: "Page",
			luxemburg: "Properties in Luxembourg",
			emirates: "Properties in United Arab Emirates",
			spain: "Properties in Spain",
			earth: "Other countries",
			success: "Success",
			successEmail: "Email sent successfully",
			failEmail: "An error occurred while sending the email",
		},
		data: {
			"Individual": "Individual",
			"Collective": "Collective",
			"Natural gas": "Natural gas",
			"Diesel": "Diesel",
			"Propane": "Propane",
			"Wood": "Wood",
			"Pellet": "Pellet",
			"Biomass": "Biomass",
			"Electricity": "Electricity",
			"Solar thermal energy": "Solar thermal energy",
			"Air heat pump": "Air heat pump",
			"Geothermal": "Geothermal",
			"Radiators": "Radiators",
			"Underfloor heating": "Underfloor heating",
			"Convectors": "Convectors",
			"Thermal emitters": "Thermal emitters",
			"Fireplaces": "Fireplaces",
			"Heat pumps": "Heat pumps",
			"Air heat pump systems": "Air heat pump systems",
			"Geothermal systems": "Geothermal systems",
			"Solar thermal panels": "Solar thermal panels",
			"Pellet stoves": "Pellet stoves",
			"Townhouse": "Townhouse",
			"Apartment": "Apartment",
			"House": "House",
			"Attic": "Penthouse",
			"Basement": "Basement",
			"Duplex": "Duplex",
			"Triplex": "Triplex",
			"Commercial Premise": "Commercial Premises",
			"Office": "Office",
			"Terrain": "Terrain",
			"Investment": "Investment",
			"Rental management": "Rental management",
		},

		adminProperties: {
			indexTitle: "Registered properties",
			indexEmptyListTitle: "You have not registered your properties yet",
			indexEmptyListDescription:
				"You can register and manage your properties from here.",
			createTitle: "New property",
			formLabelCategory: "Category",
			formLabelCountry: "Country",
			formLabelCurrency: "Currency",
			formLabelOptional: "Optional",
			formLabelTitle: "Title",
			formLabelDescription: "Description",
			formLabelAddress: "Address",
			formLabelFurnished: "Is it furnished?",
			formLabelArea: "Area",
			formLabelBedrooms: "Number of bedrooms",
			formLabelBathrooms: "Number of bathrooms",
			formLabelHeatingType: "Heating type",
			formLabelHeatingMedium: "Heating fuel",
			formLabelHeatingEnergy: "Heating energy",
			formLabelSale: "Sale",
			formLabelRent: "Rent",
			formLabelView: "View",
			formLabelPropertyType: "Property type",
			formLabelFrecuency: "Payment frequency",
			formLabelPrice: "Price",
			formLabelSufaces: "Surfaces",
			formLabelBenefits: "Benefits",
			formLabelNearPlaces: "Nearby places",
			formLabelLegalNotes: "Legal notes",
			formLabelTumbnail: "Thumbnail",
			formLabelImages: "Images",
			formLabelPhotos: "Upload photos of the property",
			formLabelPhotosDescription:
				"Once uploaded, select the image you want to use as a cover.",
			formLabelPhotosAdvertise: "Images must be less than 2MB each.",
			formLabelMap: "Indicate the location of the property on the map.",
			formLinkEdit: "Edit",
			formButtonPreview: "Preview",
			formButtonReturn: "Return",
			formButtonRegister: "Register",
			formButtonBack: "Back",
			formButtonNext: "Next",
			formButtonAddPhoto: "Add photos",
			formButtonAddSurfaces: "Add surface",
			formButtonAddBenefits: "Add benefit",
			formButtonAddNearPlaces: "Add nearby place",
			formButtonAddLegalNotes: "Add legal note",
			formOptionYes: "Yes",
			formOptionNo: "No",
			formOptionCancel: "Cancel registration",
			formPlaceholderSelect: "Select",
			formPlaceholderSelectText: "Select or type...",
			formPlaceholderSelectAdd: "Add",
			formPlaceholderText: "Type here...",
			formPlaceholderView: "Example: panoramic, partial, closed, sea view...",
			formPlaceholderSurfaces_1: "Quantity",
			formPlaceholderSurfaces_2: "Description",
			formPlaceholderSurfaces_3: "Area",
			formPlaceholderBenefits: "Example: terrace, garden, balcony...",
			formPlaceholderNearPlaces: "Example: supermarket, gym, park...",
			formPlaceholderLegalNotes:
				"Example: owner's fees, energy consumption class G...",
			formStepTitle_1: "Describe the property",
			formStepTitle_2: "Detail the space",
			formStepTitle_3: "Highlight the advantages of the property",
			formStepTitle_4: "Add a title, description and images",
			formStepTitle_5: "Set payment terms",
			formPreviewTitle: "Review the property before registering",
			formConfirmTitle: "Confirm the creation of the new property",
			formConfirmOption: "Publish property",
			formStep: "Step",
			formStepConnector: "of",
			formValidationRequired: "This field is required",
			formValidationCardDate: "This field must be in MM/YYYY format. eg: 12/2024",
			formValidationCvc: "This field must be 3 digits long.",
			formValidationNumbers: "This field only accepts numbers",
			formValidationLetters: "This field only accepts letters",
			formValidationEmail: "This field must be an email address",
			formValidationPhotos: "You must add at least one image.",
			previewSectionTitle_1: "Property Description",
			previewSectionTitle_2: "Space Details",
			previewSectionTitle_3: "Property Advantages",
			previewSectionTitle_4: "Title, Description and Images",
			previewSectionTitle_5: "Payment Terms",
			modalCreateTitle: "Confirm New Property Creation",
			modalCreateOption: "Publish Property.",
			modalPublishConfirm: "Confirm Property Publication",
			modalPauseConfirm: "Confirm Publication Pause",
			modalDeleteTitle:
				"If you delete the property, you will not be able to recover it.",
			modalDeletePauseTitle:
				"If you delete the property, you will not be able to recover it.",
			modalDeleteText:
				"You can pause the publication to keep it and reactivate it later.",
			modalDeleteButton: "Delete",
			toastDelete: "Property successfully deleted.",
			toastPublish: "Property successfully published.",
			toastPause: "Publication successfully paused.",
			actionPublish: "Publish",
			actionPause: "Pause",
			actionDetail: "View Details",
			actionPreview: "Preview",
			tabAll: "All",
			listBasic: "Basic",
			listStatus: "Status",
			listActions: "Actions",
			listActive: "Active",
			listInactive: "Inactive",
			linesPerPage: "Lines per page",
			selecteds: "selected",
			activePub: "Active Publication",
			inactivePub: "Paused Publication",
		},
		adminAffiliate: {
			indexTitle: "Affiliates",
			indexEmptyListTitle: "No affiliates have been registered yet",
			indexSearchPlaceholder: "Search affiliates",
			tabAll: "All",
			listName: "Name",
			listPhone: "Phone",
			listEmail: "Email",
			listLastPay: "Last payment",
			listStatus: "Status",
			listActions: "Actions",
			listActive: "Active",
			listInactive: "Overdue",
			linesPerPage: "Lines per page",
			selecteds: "Selected",
			detailTitle: "Renewals of ",
			detailColumn1: "Transaction number",
			detailColumn2: "Date",
			detailColumn3: "Affiliate plan",
			detailAction: "Close",
			formStepConnector: "of",

		},
		adminNav: {
			affiliateTitle: "Memberships",
			propertiesTitle: "Real estate",
			dashboardTitle: "Home",
			closeSession: "Close session",
		},
		auth: {
			login_title: "Let's log in to your account",
			login_subtitle: "Please enter your data",
			change_password_title: "Change password",
			change_password_subtitle: "Then enter your new password to reset it",
			login_email: "Email",
			login_password: "Password",
			login_password_confirm: "Confirm password",
			login_forgot: "Forgot your password?",
			login_button: "Login",
			login_remember: "Remember me",
			login_placeholder: "Type here...",
			login_email_required: "Email is required",
			login_password_required: "Password is required",
			login_password_confirmation_required: "Passwords do not match",
			forgot_password_title: "Recover password",
			forgot_password_subtitle:
				"Enter the email address you used to register. You will receive a link to reset your password.",
			email_not_found_title: "Email not registered",
			email_not_found_subtitle:
				"We can't seem to find an account associated with your email. Please make sure you entered the correct address and try again.",
			email_send_title: "Email sent",
			email_send_subtitle:
				" Enter the link sent to your email to reset your password.",
			email_send_required: "The email is required",
			email_send_validation: "The field must be an email",
			email_set_title: "Password reset",
			email_set_subtitle: "You can now continue to your work environment.",
			formButtonContinue: "Continue",
			formButtonSendLink: "Send link",
			formButtonReturn: "Return",
			formButtonChangePassword: "Change password",
			formButtonOrLogin: "Or log in",
			error_credentials: "The credentials are not correct",
			error_default: "An error has occurred",
		},
		navbar: {
			link_1: "About us",
			link_2: "Home",
			link_3: "Services",
			link_4: "Contact",
			link_5: "Membership",
			link_6: "Join",
			link_7: "Renew Membership",
			admin_1: "Properties",
		},
		footer: {
			title_1: "Contact",
			title_2: "Leave your email, and we will contact you",
			title_3: "Follow us",
			rights: "All rights reserved",
			privacy: "Privacy Policy",
			cookies: "Cookie Policy",
			terms: "Terms of Use",
		},
		home: {
			miniTitleHeader1: "Affiliate Program",
			miniTitleHeader2: "Affiliate Program",
			miniTitleHeader3: "Personalized Guidance",
			bigTitleHeader1_1: "LET'S ",
			bigTitleHeader1_2: "embark on the journey together",
			bigTitleHeader2_1: "Save ",
			bigTitleHeader2_2: "up to 50%",
			bigTitleHeader3_1: "Empower ",
			bigTitleHeader3_2: "your move",
			commonHeader1: "With our affiliate program, you participate in incredible promotions to start your new life in Luxembourg.",
			commonHeader2: "And make your move to Luxembourg more affordable with our affiliate program.",
			commonHeader3: "Receive personalized advice and support from our relocation experts through video calls.",
			actionButtonHeader1: "Learn more",
			actionButtonHeader2: "Learn more",
			actionButtonHeader3: "Learn more",
			sectionPartners: "These companies already trust us",
			sectionButton_1: "Schedule an Appointment",
  			sectionButton_2: "Learn More",
			titleHeader_1: "With Libling Solutions, ",
			titleHeader_2: "your relocation to Luxembourg ",
			titleHeader_3: "is easy and secure.",
			subtitleHeader_1: " ",
			subtitleHeader_2: " ",
			sectionMiniTitle_1: "Personalized Assistance",
			sectionMiniTitle_2: "Discover Our Plans",
			sectionMiniTitle_3: "Comprehensive Consulting",
			sectionTitle_1:
				"We are by your side to assist you with whatever you need",
			sectionContent_1:
				"Providing you with comprehensive service and optimal support in your relocation process to Luxembourg 🇱🇺.",
			sectionTitle_2: "Together, we can achieve it",
			sectionContent_2:
				"Starting in a different country can sometimes be challenging, but don't worry; we are with you to simplify administrative processes and help you integrate quickly into the Luxembourgish community.",
			sectionTitle_3: "Our services",
			sectionList_3: [
				"Visit or settle in the Grand Duchy",
				"Search or buy/sell real estate",
				"Personalized advice",
				"Tours and points of interest",
			],
			sectionTitle_4: "We help you manage and advise you",
			sectionList_4: [
				"Work permit application/temporary authorization.",
				"Search for a house or apartment.",
				"Search for a school and daycare for your children.",
				"Real estate market, buying and selling services, rental and property management.",
				"Real estate advice.",
				"Organisation of the move.",
			],
			reviewName_1: "MARIA SMITH",
			reviewDescription_1:
				"'I have been living in Luxembourg for 1 month thanks to Libling. I found a job in the technology sector, where I specialize the most. They also helped me with opening a bank account, residence permit application, and making friends in Luxembourg.'",
			reviewName_2: "LUIS MORENO",
			reviewDescription_2:
				"'My name is Luis Moreno, and I am from Peru. My girlfriend and I decided to move to Luxembourg in search of a better future for both of us a year ago. We sought the assistance of Libling, and it was definitely one of the best decisions we could have made.'",
			reviewName_3: "LAURA MARTINEZ",
			reviewDescription_3:
				"'Hello, I'm Laura from Mexico. Luxembourg has always been a magnificent city with great opportunities for me, so I contacted Libling to get the necessary requirements to live there. I recommend them 100%.'",
		},
		services: {
			bigTitleHeader1_1: "Moving to Luxembourg has never been easier",
			commonHeader1: "Ensure your move to Luxembourg with the professional guidance of ",
			commonHeader2: "Libling Solutions",
			commonHeader3: ", at your service.",
			sectionTitle_1: "Affiliations",
			sectionSubtitle_1: "Try our affiliations now",
			sectionContent_1_1: "Choose the plan ",
			sectionContent_1_2: "that best suits your needs and budget:",
			sectionOption1: "1 Month",
			sectionOption2: "6 months",
			sectionOption3: "1 Year",
			sectionOptionBy1: "month",
			sectionOptionBy2: "semester",
			sectionOptionBy3: "year",
			planActionButton:"Apply",
			planTitle1:"Student",
			planContent1:"Study in Luxembourg.",
			planList1: ["Updates", "Upcoming events and opportunities for international students", "Advice on how to apply and where to settle in", "Exclusive access to information about universities, programs, scholarships, and student housing options", "Q&A Session"],
			planList1Extra: ["Updates", "Upcoming events and opportunities for international students", "Advice on how to apply and where to settle in", "Exclusive access to information about universities, programs, scholarships, and student housing options", "Q&A Session", "Ongoing support throughout your adaptation process", "Full processing of documents and authorizations", "⁠Housing search and support with the relocation process", "2 days of personalized assistance"],
			planTitle2: "Job Seeker",
			planContent2: "Settle in Luxembourg",
			planList2: ["Exclusive access to guides for finding work, applying for visas, and navigating the relocation process", "Curated resources on companies, cost of living, and life in Luxembourg", "Subscription to webinars with industry experts on job search strategies"],
			planList2Extra: ["Exclusive access to guides for finding work, applying for visas, and navigating the relocation process", "Curated resources on companies, cost of living, and life in Luxembourg", "Subscription to webinars with industry experts on job search strategies", "2 days of personalized assistance"],
			planTitle3: "Entrepreneur",
			planContent3: "Start a business in Luxembourg",
			planList3: ["Comprehensive guidance on business, setup, legal requirements, and licenses", "Access to online consultations on topics such as financing, marketing, and team formation in Luxembourg", "Challenges in launching a business in Luxembourg"],
			planList3Extra: ["Comprehensive guidance on business, setup, legal requirements, and licenses", "Access to online consultations on topics such as financing, marketing, and team formation in Luxembourg", "Challenges in launching a business in Luxembourg", "Requirements and documents needed for an entrepreneur/investor visa application", "2 days of personalized assistance"],
			sectionSubtitle_2: "Benefits of being Libling Affilates",
			sectionList_2: ["Discounts on services and packages","Personalized call sessions","Personalized guidance","Video calls to clarify doubts","Up to 50% discount on your second service package","Constant updates","Access to programs, workshops and exclusive information"],
			sectionTitle_3: "Our Packages",
			sectionSubtitle_3: "Your path to a new life in Luxembourg",
			sectionContent_3: "Choose the plan that best suits your needs and budget:",
			packageTitle1:"Basic",
			packageList1:["Initial assistance on arrival.", "Management of essential administrative procedures.", "Registration for basic services (electricity, water, internet)."],
			packageTitle2:"Premium",
			packageList2:["Comprehensive assistance in all aspects of your new life.", "Complete management of administrative and legal procedures.", "Housing search and personalized support during the move.", "Guidance for choosing the ideal school for your children.", "Temporary accommodation in a comfortable environment.", "Reception and transfer from the airport.", "3-day orientation tour with personalized assistance."],
			packageTitle3:"Standard",
			packageList3:["Continuous assistance during your adaptation process.", "Complete processing of documents and permits.", "Housing search and support in the relocation process.", "Guidance for choosing the ideal school for your children.", "2 days of personalized assistance."],
			sectionTitle_4: "Additional Consultations",
			sectionSubtitle_4: "More than a company, we are a team at your service",
			sectionContent_4: "At Libling, we have a team of experts in various fields to offer you comprehensive support.",
			aditionalConsultTitle_1: "Real Estate Consulting",
			aditionalConsultContent_1: "Our team of experts will provide you with personalized advice to help you make the best decision for you and your family.",
			aditionalConsultTitle_2: "Architecture, Construction and Investment Consulting",
			aditionalConsultContent_2: "We provide you with real estate investment advice so that you can obtain the maximum return on your capital.",
			aditionalConsultTitle_3: "Legal Guidance",
			aditionalConsultContent_3: "We offer you comprehensive legal advice so that you feel safe and protected in Luxembourg.",
			aditionalConsultTitle_4: "Medical Consultations",
			aditionalConsultContent_4: "Your health is the most important thing. That's why we guide you through the process of finding the right specialist.",
			aditionalConsultTitle_5: "Integration into the country's social and cultural life",
			aditionalConsultContent_5: "We will notify you of activities and events so that you can enjoy your new life to the fullest.",
			aditionalConsultTitle_6: "Personalized attention on your trip and move",
			aditionalConsultContent_6: "We will take care of the details! From planning your trip to settling into your new home.",
			sectionTitle_5: "There's More",
			sectionSubtitle_5: "Additional Services for Your Convenience",
			aditionalService_1: "Airport reception and transfer.",
			aditionalService_2: "Trip and relocation planning.",
			aditionalService_3: "Assistance with cleaning and maintenance services.",
			contactTitle: "Take the First Step Towards Your New Life Now",
			contactActionButton: "Schedule an Appointment",
			formPageLabel_1: "Personal Information",
			formPageLabel_2: "Payment Details",
			formTitle_1: "Basic Information",
			formTitle_2: "Tell us your email address",
			modalTitle: "Selected Plan",
			inputLabel_1: "Name",
			inputPlaceholder_1: "Enter your name",
			inputLabel_2: "Phone",
			inputPlaceholder_2: "Enter your phone number",
			inputLabel_3: "Email",
			inputPlaceholder_3: "Email address",
			inputLabel_4: "Country",
			inputPlaceholder_4: "Select your country",
			inputLabel_5: "Observation",
			inputPlaceholder_5: "Write here...",
			inputLabel_6: "Card Number",
			inputPlaceholder_6: "Enter your card number",
			inputLabel_7: "Name",
			inputPlaceholder_7: "Enter your name",
			inputLabel_8: "Expires",
			inputPlaceholder_8: "Expiration date",
			inputLabel_9: "CVC",
			inputPlaceholder_9: "Enter the CVC code",
			inputLabel_10: "Country",
			inputPlaceholder_10: "Select your country",
			inputLabel_11: "Province",
			inputPlaceholder_11: "Select",
			inputLabel_12: "Postal Code",
			inputPlaceholder_12: "Enter the postal code",
			buttonAction_1: "Exit",
			buttonAction_2: "Next Step",
			buttonAction_3: "Back",
			buttonAction_4: "Join",
			buttonAction_5: "Choose a Different Plan",
			priceLabel: "Subtotal",
			successMessageTitle: "Your membership was successful.",
			successMessageContent: "Please check your email.",
			errorMessageTitle: "Your affiliation could not be processed.",
			errorMessageContent: "Your payment information could not be verified.",
			infoMessageTitle: "We are verifying your payment.",
			infoMessageContent: "Please do not leave this page while we verify your payment.",
			errorFindAffiliate: "This email is not affiliated",
			priceTotalLabel: "Total",
  			feeLabel: "Tax",
			planDate: "Cut-off date",
  			plan: "Plan"

		},
		contact: {
			miniTitleHeader1: "Embark on the adventure",
			bigTitleHeader1: "Schedule your appointment now!",
			formTitle1: "Choose a day for us to contact you",
			formTitle2: "Tell us a little bit about yourself",
			formLabelName: "Full Name",
			formPlaceholderName: "Enter your full name",
			formLabelSubject: "Topic of Interest",
			formPlaceholderSubject: "Select",
			formLabelEmail: "Email Address",
			formPlaceholderEmail: "Eg.: example@email.com",
			formLabelMessage: "Message",
			formPlaceholderMessage: "Tell us why you're contacting us",
			formActionButton: "Schedule Appointment",
			formSubjectList: [
				{
					"key": "job",
					"value": "I want to work in Luxembourg"
				},
				{
					"key": "jobs",
					"value": "I want to know about jobs in Luxembourg"
				},
				{
					"key": "job_permit",
					"value": "I want information about work permits"
				},
				{
					"key": "business",
					"value": "I want to start a business in Luxembourg"
				},
				{
					"key": "study",
					"value": "I want to study in Luxembourg"
				},
				{
					"key": "languages",
					"value": "I want to learn languages in Luxembourg"
				},
				{
					"key": "stay",
					"value": "I want to know where to stay in Luxembourg"
				},
				{
					"key": "investment",
					"value": "I want to invest in Luxembourg"
				}
			],

			calendarTitle: "Select a date",
			sectionTitle_1: "Schedule with us !",
			sectionContent_1:
				"Do you want to have a meeting with Libling Solutions? We are at your complete disposal to provide you with comprehensive service.",
			sectionTitle_2: "We will always keep you informed of everything",
			sectionContent_2:
				"Because you are our priority. Subscribe to our newsletter to be the first to receive all our updates, news, products, and services.",
			form_name: "Names",
			form_subject: "Subject",
			form_email: "E-mail",
			form_message: "Message",
			form_button: "Send",
		},
		about: {
			headerTitle_1: "Embark on the Adventure!",
			headerSubtitle_1: "Are you looking for a fresh start in the heart of Europe?",
			headerContent_1_1: "Libling Solutions",
			headerContent_1_2: " supports you every step of the way towards a bright future in ",
			headerContent_1_3: "Luxembourg.",
			actionButton_1: "Learn what Libling has to offer you",
			sectionTitle_1: "Get to know us",
			sectionSubtitle_1: "Who are we",
			sectionContent_1_1: "Libling Solutions",
			sectionContent_1_2: " is dedicated to transforming your relocation to",
			sectionContent_1_3: " Luxembourg",
			sectionContent_1_4: " into a positive experience. Our multilingual team offers expert guidance and personalized support, handling everything from housing searches to immigration formalities. We prioritize clear communication and your well-being, ensuring a smooth and stress-free relocation. Let us help you make Luxembourg your home with ease and confidence.",
			actionButton_1_1: "Learn more",
			sectionTitle_2: "Professionalism",
			sectionSubtitle_2: "Innovators in Relocation and Real Estate in the Grand Duchy",
			sectionContent_2_1: "At ",
			sectionContent_2_2: "Libling Solutions",
			sectionContent_2_3: ", we offer comprehensive services to meet all your relocation and real estate needs. We believe that moving to a new home should be a pleasant and personalized experience, ensuring you and your family enjoy a smooth transition. Trust us to deliver excellence in every step of your relocation process.",
			actionButton_2: "Learn more",
			sectionTitle_3: "Excellent service",
			sectionSubtitle_3: "Our goal is your well-being",
			sectionContent_3_1: "Libling Solutions",
			sectionContent_3_2: " aims to support, help and facilitate everything for you so that your move to the Grand Duchy is pleasant and comfortable. We have a team of professionals specialized in each of your needs and in your language. Our priority is to provide you with a quality service.",
			actionButton_3: "Learn more",
			sectionTitle_4: "Contact us",
			sectionSubtitle_4_1: "Start your journey to Luxembourg with ",
			sectionSubtitle_4_2: "Libling Solutions",
			sectionContent_4: "Contact our team today and find out how we can help you create a new home.",
			actionButton_4: "I want to schedule an appointment",
		},
		mail: {
			main: "I would like to know more about Libling",
			subject_1: "Information",
			subject_2: "Services",
			subject_3: "Greetings",
			package: "I am interested by the following pack: ",
			date: "Hello, I would like an appointment for the day: ",
			notify: "Your message was sent with success",
			failed: "Your request could not be completed",
			infoContent1:"Thank you for contacting us",
			infoContent2:". We have received your message and will get back to you as soon as possible.",

			affiliateTitle: "Thank you for joining our family",
			affiliateTitleAdmin: "A new affiliate payment has been registered",
			affiliateContent_1: "Welcome!",
			affiliateContent_2: "At Libling, we are delighted that you have joined our affiliate program.",
			affiliateContent_3: "Your decision to be part of our community fills us with joy and motivates us to continue offering the best service to those seeking a new beginning in Luxembourg.",
			affiliateContent_4: "As an affiliate, you have access to exclusive benefits and ongoing support from our team of experts.",
			affiliateContent_5: "Together we can achieve great things and help many people fulfill their dreams!",
			contentBottom: "The Libling Team.",

			footerTopTitle: "We are here to serve you",
			footerTopText_1: "Do you have any questions?",
			footerTopText_2: " Write to us at ",
			footerTopText_3: "info@libling.com",
			footerTopText_4: " and we will be in touch with you as soon as possible. You can also leave us comments about our services at ",
			footerTopText_5: "info@libling.lu",
			footerBottomText_1: "Terms",
			footerBottomText_2: "Privacy",
			footerBottomText_3: "Contact Us",
			footerBottomText_4: "Unsubscribe",
		},
	},
	fr: {
		immo: {
			headerTitle: "Votre bien immobilier idéale vous attend",
			headerDescription:
				"Opportunités immobilières uniques au Luxembourg, en Espagne et à Dubaï : ne les manquez pas !",
			headerButton: "Recherche",
			sectionTitle_1: "Découvrez votre nouvel espace",
			sectionDescription_1:
				"Soyez le premier à connaître les propriétés nouvellement disponibles sur le marché.",
			sectionTitle_2: "Confort et sécurité pour vous et votre famille",
			sectionDescription_2:
				"Profitez de maisons confortables et sécurisées pour créer des souvenirs inoubliables.",
			sectionTitle_3: "Démarrez votre entreprise idéale",
			sectionDescription_3:
				"Trouvez des locaux commerciaux et des bureaux parfaits pour développer votre entreprise, dans des emplacements stratégiques.",
			sectionTitle_4: "Prêt à emménager",
			sectionDescription_4:
				"Des biens immobiliers avec tout ce dont vous avez besoin pour commencer à profiter de votre nouvelle maison dès le premier instant.",
			sectionTitle_5: "Espace pour toute la famille",
			sectionDescription_5:
				"Les propriétés les plus spacieuses avec plusieurs chambres et salles de bain.",
			contactTitle: "Votre avenir commence ici",
			contactDescription:
				"Libling Immo est votre allié idéal pour trouver la propriété de vos rêves.",
			contactFormTitle:
				"Laissez-nous vos coordonnées et nous vous contacterons",
			contactFormButton: "Envoyer",
			miniatureConector: "à",
			altConector: "à",
			backList: "Retour à la liste",
			backSearch: "Retour à la recherche",
			askFor: "Demander",
			results: "résultats",
			page: "Page",
			luxemburg: "Propriétés au Luxembourg",
			emirates: "Propriétés aux Émirats arabes unis",
			spain: "Propriétés en Espagne",
			earth: "Autres pays",
			success: "Succès",
			successEmail: "Email envoyé avec succès",
			failEmail: "Une erreur est survenue lors de l'envoi de l'email",
		},
		data: {
			"Individual": "Individuel",
			"Collective": "Collectif",
			"Natural gas": "Gaz naturel",
			"Diesel": "Gasóleo",
			"Propane": "Propano",
			"Wood": "Leña",
			"Pellet": "Pellet",
			"Biomass": "Biomasa",
			"Electricity": "Electricidad",
			"Solar thermal energy": "Energía solar térmica",
			"Air heat pump": "Bomba de calor",
			"Geothermal": "Geotermia",
			"Radiators": "Radiadores",
			"Underfloor heating": "Suelo radiante",
			"Convectors": "Convectores",
			"Thermal emitters": "Emisores térmicos",
			"Fireplaces": "Chimeneas",
			"Heat pumps": "Bombas de calor",
			"Air heat pump systems": "Sistemas de aerotermia",
			"Geothermal systems": "Sistemas de geotermia",
			"Solar thermal panels": "Paneles solares térmicos",
			"Pellet stoves": "Estufas de pellet",
			"Townhouse": "Maison de ville",
			"Apartment": "Appartement",
			"House": "Maison",
			"Attic": "Attique",
			"Basement": "Sous-sol",
			"Duplex": "Duplex",
			"Triplex": "Triplex",
			"Commercial Premise": "Local commercial",
			"Office": "Bureau",
			"Terrain": "Terrain",
			"Investment": "Investissement",
			"Rental management": "Gestión locative",
		},

		adminProperties: {
			indexTitle: "Propriétés enregistrées",
			indexEmptyListTitle: "Vous n'avez pas encore enregistré vos propriétés",
			indexEmptyListDescription:
				"Vous pouvez enregistrer et gérer vos propriétés à partir d'ici.",
			createTitle: "Nouvelle propriété",
			formLabelCategory: "Catégorie",
			formLabelCountry: "Pays",
			formLabelCurrency: "Devise",
			formLabelOptional: "Optionnel",
			formLabelTitle: "Titre",
			formLabelDescription: "Description",
			formLabelAddress: "Adresse",
			formLabelFurnished: "Est-il meublé ?",
			formLabelArea: "Superficie",
			formLabelBedrooms: "Nombre de chambres",
			formLabelBathrooms: "Nombre de salles de bain",
			formLabelHeatingType: "Type de chauffage",
			formLabelHeatingMedium: "Combustible de chauffage",
			formLabelHeatingEnergy: "Énergie de chauffage",
			formLabelSale: "Acheter",
			formLabelRent: "Louer",
			formLabelView: "Vue",
			formLabelPropertyType: "Type de bien",
			formLabelFrecuency: "Fréquence de paiement",
			formLabelPrice: "Prix",
			formLabelSufaces: "Surfaces",
			formLabelBenefits: "Avantages",
			formLabelNearPlaces: "Lieux à proximité",
			formLabelLegalNotes: "Notes légales",
			formLabelTumbnail: "Vignette",
			formLabelImages: "Images",
			formLabelPhotos: "Téléchargez des photos du bien",
			formLabelPhotosDescription:
				"Une fois chargées, sélectionnez l'image que vous souhaitez utiliser comme couverture.",
			formLabelPhotosAdvertise:
				"Les images doivent peser moins de 2 Mo chacune.",
			formLabelMap: "Indiquez l'emplacement de la propriété sur la carte.",
			formLinkEdit: "Modifier",
			formButtonPreview: "Aperçu",
			formButtonReturn: "Retour",
			formButtonRegister: "Enregistrer",
			formButtonBack: "Précédent",
			formButtonNext: "Suivant",
			formButtonAddPhoto: "Ajouter des photos",
			formButtonAddSurfaces: "Ajouter une surface",
			formButtonAddBenefits: "Ajouter un avantage",
			formButtonAddNearPlaces: "Ajouter un lieu à proximité",
			formButtonAddLegalNotes: "Ajouter une note légale",
			formOptionYes: "Oui",
			formOptionNo: "Non",
			formOptionCancel: "Annuler l'enregistrement",
			formPlaceholderSelect: "Sélectionner",
			formPlaceholderSelectText: "Sélectionnez ou tapez...",
			formPlaceholderSelectAdd: "Ajouter",
			formPlaceholderText: "Tapez ici...",
			formPlaceholderView: "Exemple: panoramique, partiel, fermé, vue mer...",
			formPlaceholderSurfaces_1: "Quantité",
			formPlaceholderSurfaces_2: "Description",
			formPlaceholderSurfaces_3: "Superficie",
			formPlaceholderBenefits: "Exemple: terrasse, jardin, balcon...",
			formPlaceholderNearPlaces: "Exemple: supermarché, gymnase, parc...",
			formPlaceholderLegalNotes:
				"Exemple: frais de propriétaire, consommation énergétique classe G...",
			formStepTitle_1: "Décrivez la propriété",
			formStepTitle_2: "Détaillez l'espace",
			formStepTitle_3: "Mettez en valeur les avantages de la propriété",
			formStepTitle_4: "Ajoutez un titre, une description et des images",
			formStepTitle_5: "Définir les conditions de paiement",
			formPreviewTitle: "Vérifiez la propriété avant de vous inscrire",
			formConfirmTitle: "Confirmer la création de la nouvelle propriété",
			formConfirmOption: "Publier la propriété",
			formStep: "Étape",
			formStepConnector: "de",
			formValidationRequired: "Ce champ est obligatoire",
			formValidationCardDate: "Ce champ doit être au format MM/AAAA. ex: 12/2024",
			formValidationCvc: "Ce champ doit comporter 3 chiffres.",
			formValidationNumbers: "Ce champ n'accepte que des chiffres",
			formValidationLetters: "Ce champ n'accepte que des lettres",
			formValidationEmail: "Ce champ doit être une adresse e-mail",
			formValidationPhotos: "Vous devez ajouter au moins une image.",
			previewSectionTitle_1: "Description du bien",
			previewSectionTitle_2: "Détails de l'espace",
			previewSectionTitle_3: "Avantages du bien",
			previewSectionTitle_4: "Titre, description et images",
			previewSectionTitle_5: "Conditions de paiement",
			modalCreateTitle: "Confirmer la création d'un nouveau bien",
			modalCreateOption: "Publier un bien.",
			modalPublishConfirm: "Confirmer la publication du bien",
			modalPauseConfirm: "Confirmer la pause de la publication",
			modalDeleteTitle:
				"Si vous supprimez le bien, vous ne pourrez plus le récupérer.",
			modalDeletePauseTitle:
				"Si vous supprimez le bien, vous ne pourrez plus le récupérer.",
			modalDeleteText:
				"Vous pouvez suspendre la publication pour la conserver et la réactiver ultérieurement.",
			modalDeleteButton: "Supprimer",
			toastDelete: "Le bien a été supprimé avec succès.",
			toastPublish: "Le bien a été publié avec succès.",
			toastPause: "La publication a été suspendue avec succès.",
			actionPublish: "Publier",
			actionPause: "Suspendre",
			actionDetail: "Voir les détails",
			actionPreview: "Aperçu",
			tabAll: "Tous",
			listBasic: "Basique",
			listStatus: "État",
			listActions: "Actions",
			listActive: "Actif",
			listInactive: "Inactif",
			linesPerPage: "Lignes par page",
			selecteds: "sélectionnés",
			activePub: "Publication active",
			inactivePub: "Publication suspendue",
		},
		adminAffiliate: {
			indexTitle: "Affiliés",
			indexEmptyListTitle: "Aucun affilié n'a encore été enregistré",
			indexSearchPlaceholder: "Rechercher des affiliés",
			tabAll: "Tous",
			listName: "Nom",
			listPhone: "Téléphone",
			listEmail: "Courriel",
			listLastPay: "Dernier paiement",
			listStatus: "Statut",
			listActions: "Actions",
			listActive: "Actif",
			listInactive: "En retard",
			linesPerPage: "Lignes par page",
			selecteds: "Sélectionnés",
			detailTitle: "Renouvellements de ",
			detailColumn1: "Numéro de transaction",
			detailColumn2: "Date",
			detailColumn3: "Plan d'affiliation",
			detailAction: "Fermer",
			formStepConnector: "de",

		},
		adminNav: {
			affiliateTitle: "Affiliations",
			propertiesTitle: "Immobilier",
			dashboardTitle: "Home",
			closeSession: "Fermer la session",
		},
		auth: {
			login_title: "Nous allons nous connecter à votre compte",
			login_subtitle: "Veuillez saisir vos coordonnées",
			change_password_title: "Modifier le mot de passe",
			change_password_subtitle:
				"Saisissez ensuite votre nouveau mot de passe pour le réinitialiser",
			login_email: "E-mail",
			login_password: "Mot de passe",
			login_password_confirm: "Répéter le mot de passe",
			login_forgot: "Vous avez oublié votre mot de passe?",
			login_button: "Se connecter",
			login_remember: "Souvenez-vous de moi",
			login_placeholder: "Tapez ici...",
			login_email_required: "Le courrier est obligatoire",
			login_password_required: "Le mot de passe est requis",
			login_password_confirmation_required:
				"les mots de passe ne correspondent pas",
			forgot_password_title: "Récupérer le mot de passe",
			forgot_password_subtitle:
				"Entrez l'adresse électronique que vous avez utilisée pour vous inscrire. Vous recevrez un lien pour réinitialiser votre mot de passe",
			email_not_found_title: "Email non enregistré",
			email_not_found_subtitle:
				"Nous ne parvenons pas à trouver un compte associé à votre adresse électronique. Veuillez vous assurer que vous avez saisi l'adresse correcte et réessayez",
			email_send_title: "Email envoyé",
			email_send_subtitle:
				"Saisissez le lien envoyé à votre adresse électronique pour réinitialiser votre mot de passe",
			email_send_required: "L'email est obligatoire",
			email_send_validation: "Le champ doit être un courriel",
			email_set_title: "Réinitialisation du mot de passe",
			email_set_subtitle: "Vous pouvez maintenant continuer à travailler",
			formButtonContinue: "Continuer",
			formButtonSendLink: "Envoyer le lien",
			formButtonReturn: "Retour",
			formButtonChangePassword: "Modifier le mot de passe",
			formButtonOrLogin: "Ou se connecter",
			error_credentials:
				"Les informations d'identification ne sont pas correctes",
			error_default: "Une erreur s'est produite",
		},
		navbar: {
			link_1: "A propos de nous",
			link_2: "Accueil",
			link_3: "Services",
			link_4: "Contact",
			link_5: "Adhésion",
			link_6: "Adhérer",
			link_7: "Renouveler mon adhésion",
			admin_1: "Propriétés",
		},
		footer: {
			title_1: "Contact",
			title_2: "Laissez nous votre e-mail et nous vous recontacterons",
			title_3: "Suivez-nous",
			rights: "Tous droits réservés",
			privacy: "Politique de confidentialité",
			cookies: "Politique de cookies",
			terms: "Conditions d'utilisation",
		},
		home: {
			miniTitleHeader1: "Programme d'affiliation",
			miniTitleHeader2: "Programme d'affiliation",
			miniTitleHeader3: "Accompagnement personnalisé",
			bigTitleHeader1_1: "COMMENCEZ ",
			bigTitleHeader1_2: "le voyage ensemble",
			bigTitleHeader2_1: "Économisez ",
			bigTitleHeader2_2: "jusqu'à 50%",
			bigTitleHeader3_1: "Renforcez ",
			bigTitleHeader3_2: "votre déménagement",
			commonHeader1: "Avec notre programme d'affiliation, vous participez à des promotions incroyables pour démarrer votre nouvelle vie au Luxembourg.",
			commonHeader2: "Et rendez votre déménagement au Luxembourg plus abordable grâce à notre programme d'affiliation.",
			commonHeader3: "Bénéficiez de conseils et d'un soutien personnalisés de la part de nos experts en relocalisation par visioconférence.",
			actionButtonHeader1: "En savoir plus",
			actionButtonHeader2: "En savoir plus",
			actionButtonHeader3: "En savoir plus",
			sectionPartners: "Ces entreprises nous font déjà confiance",
			sectionButton_1: "Prendre rendez-vous",
  			sectionButton_2: "En savoir plus",
			titleHeader_1: "Avec Libling Solutions,",
			titleHeader_2: "votre installation au Luxembourg",
			titleHeader_3: "est facile et sécurisée.",
			subtitleHeader_1: " ",
			subtitleHeader_2: " ",
			sectionMiniTitle_1: "Assistance personnalisée",
			sectionMiniTitle_2: "Découvrez nos forfaits",
			sectionMiniTitle_3: "Conseil complet",
			sectionTitle_1:
				"Nous sommes à vos côtés pour vous aider en tout ce dont vous avez besoin",
			sectionContent_1:
				"En vous fournissant un service complet et un soutien optimal dans votre processus d'installation au Luxembourg 🇱🇺",
			sectionTitle_2: "Ensemble, nous pouvons y arriver",
			sectionContent_2:
				"Tout recommencer dans un pays différent peut parfois être un défi, mais ne vous inquiètez pas. Nous serons à vos côtés pour faciliter vos processus administratifs, légaux et culturels afin que vous puissiez vous adapter rapidement à la communauté luxembourgeoise.",
			sectionTitle_3: "Nos services",
			sectionList_3: [
				"Visiter ou s'installer dans le Grand-Duché",
				"Recherche ou achat/vente de biens immobiliers",
				"Conseils personnalisés",
				"Visites et points d'intérêt",
			],
			sectionTitle_4: "Nous vous aidons à gérer et nous vous conseillons",
			sectionList_4: [
				"Demande de permis de travail/autorisation temporaire.",
				"Recherche de maison ou d'appartement.",
				"Recherche d'école et de garderie pour vos enfants.",
				"Marché immobilier, services d'achat et de vente, location et gestion immobilière.",
				"Conseils immobiliers.",
				"Organisation du déménagement.",
			],
			reviewName_1: "MARIA SMITH",
			reviewDescription_1:
				"'Cela fait 1 mois que je vis au Luxembourg grâce à Libling. J'ai trouvé un emploi dans le secteur de la technologie, là où je suis le plus spécialisé. Ils m'ont également aidé à ouvrir un compte bancaire, à faire la demande de permis de résidence et à me faire des amis au Luxembourg.'",
			reviewName_2: "LUIS MORENO",
			reviewDescription_2:
				"'Je m'appelle Luis Moreno et je viens du Pérou. Ma copine et moi avons décidé de partir au Luxembourg à la recherche d'un meilleur avenir pour nous deux il y a un an. Nous avons sollicité l'aide de Libling, et c'était certainement l'une des meilleures décisions que nous aurions pu prendre.'",
			reviewName_3: "LAURA MARTINEZ",
			reviewDescription_3:
				"'Bonjour, je m'appelle Laura et je viens du Mexique. Luxembourg a toujours été une ville magnifique avec de grandes opportunités pour moi, alors j'ai contacté Libling pour obtenir les requis nécessaires pour y vivre. Je les recommande à 100%.'",
		},
		services: {
			bigTitleHeader1_1: "Déménager au Luxembourg n'a jamais été aussi facile",
			commonHeader1: "Assurez votre déménagement au Luxembourg avec l'accompagnement professionnel de ",
			commonHeader2: "Libling Solutions",
			commonHeader3: ", à votre service.",
			sectionTitle_1: "Affiliations",
			sectionSubtitle_1: "Essayez nos affiliations maintenant",
			sectionContent_1_1: "Choisissez le plan ",
			sectionContent_1_2: "qui correspond le mieux à vos besoins et à votre budget:",
			sectionOption1: "1 mois",
			sectionOption2: "6 mois",
			sectionOption3: "1 an",
			sectionOptionBy1: "mois",
			sectionOptionBy2: "semestre",
			sectionOptionBy3: "an",
			planActionButton:"Demander",
			planTitle1:"Étudiant",
			planContent1:"Étudier au Luxembourg.",
			planList1:["Mises à jour", "Événements et opportunités futures pour les étudiants internationaux", "Conseils sur la manière de postuler et où s'installer", "Accès exclusif à des informations sur les universités, les programmes, les bourses et les options de logement pour les étudiants", "Session de questions et réponses"],
			planList1Extra:["Mises à jour", "Événements et opportunités futures pour les étudiants internationaux", "Conseils sur la manière de postuler et où s'installer", "Accès exclusif à des informations sur les universités, les programmes, les bourses et les options de logement pour les étudiants", "Session de questions et réponses", "Accompagnement continu tout au long de votre processus d'adaptation", "Traitement complet des documents et autorisations.","⁠Recherche de logement et accompagnement dans le processus de déménagement.","2 jours d'assistance personnalisée"],
			planTitle2:"Demandeur d'emploi",
			planContent2:"S'installer au Luxembourg.",
			planList2:["Accès exclusif à des guides pour trouver du travail, demander des visas et naviguer dans le processus de réinstallation", "Ressources sélectionnées sur les entreprises, le coût de la vie et la vie au Luxembourg", "Abonnement à des webinaires avec des experts de l'industrie sur les stratégies de recherche d'emploi"],
			planList2Extra:["Accès exclusif à des guides pour trouver du travail, demander des visas et naviguer dans le processus de réinstallation", "Ressources sélectionnées sur les entreprises, le coût de la vie et la vie au Luxembourg", "Abonnement à des webinaires avec des experts de l'industrie sur les stratégies de recherche d'emploi", "2 jours d'assistance personnalisée."
				],
			planTitle3:"Entrepreneur",
			planContent3:"Créer une entreprise au Luxembourg.",
			planList3:["Orientation complète sur les affaires, la configuration, les exigences légales et les licences", "Accès à des consultations en ligne sur des sujets tels que le financement, le marketing et la formation d'une équipe au Luxembourg", "Défis liés au lancement d'une entreprise au Luxembourg"],
			planList3Extra:["Orientation complète sur les affaires, la configuration, les exigences légales et les licences", "Accès à des consultations en ligne sur des sujets tels que le financement, le marketing et la formation d'une équipe au Luxembourg", "Défis liés au lancement d'une entreprise au Luxembourg", "Exigences et documents nécessaires à la demande de visa de entrepreneur/ investisseur.", "2 jours d'assistance personnalisée."],
			sectionSubtitle_2: "Avantages de faire partie de nos affiliés",
			sectionList_2: ["Remises sur les services et les forfaits","Séances d'appels personnalisées","Conseils personnalisés","Appels vidéo pour éclaircir vos doutes","Jusqu'à 50% de réduction sur votre deuxième forfait de services","Mises à jour constantes","Accès à des programmes, des ateliers et des informations exclusives"],
			sectionTitle_3: "Nos forfaits",
			sectionSubtitle_3: "Votre chemin vers une nouvelle vie au Luxembourg",
			sectionContent_3: "Choisissez le plan qui correspond le mieux à vos besoins et à votre budget:",
			packageTitle1:"Basique",
			packageList1:["Assistance initiale à l'arrivée.", "Gestion des démarches administratives essentielles.", "Inscription aux services de base (électricité, eau, internet)."],
			packageTitle2:"Premium",
			packageList2:["Assistance complète dans tous les aspects de votre nouvelle vie.", "Gestion complète des démarches administratives et juridiques.", "Recherche de logement et accompagnement personnalisé lors du déménagement.", "Conseils pour choisir l'école idéale pour vos enfants.", "Hébergement temporaire dans un environnement confortable.", "Accueil et transfert depuis l'aéroport.", "Visite d'orientation de 3 jours avec assistance personnalisée."],
			packageTitle3:"Standard",
			packageList3:["Accompagnement continu tout au long de votre processus d'adaptation.", "Traitement complet des documents et autorisations.", "Recherche de logement et accompagnement dans le processus de déménagement.", "Conseils pour choisir l'école idéale pour vos enfants.", "2 jours d'assistance personnalisée."],
			sectionTitle_4: "Consultations supplémentaires",
			sectionSubtitle_4: "Plus qu'une entreprise, nous sommes une équipe à votre service",
			sectionContent_4: "Chez Libling, nous disposons d'une équipe d'experts dans divers domaines pour vous offrir un soutien complet.",
			aditionalConsultTitle_1: "Conseil immobilier",
			aditionalConsultContent_1: "Notre équipe d'experts vous fournira des conseils personnalisés pour vous aider à prendre la meilleure décision pour vous et votre famille.",
			aditionalConsultTitle_2: "Conseil en architecture, construction et investissement",
			aditionalConsultContent_2: "Nous vous conseillons en matière d'investissement immobilier afin que vous puissiez obtenir le meilleur rendement de votre capital.",
			aditionalConsultTitle_3: "Orientation juridique et légale",
			aditionalConsultContent_3: "Nous vous proposons un conseil juridique complet pour que vous vous sentiez en sécurité et protégé au Luxembourg.",
			aditionalConsultTitle_4: "Consultations médicales",
			aditionalConsultContent_4: "Votre santé est la chose la plus importante. C'est pourquoi nous vous guidons dans le processus de recherche du spécialiste approprié.",
			aditionalConsultTitle_5: "Intégration à la vie sociale et culturelle du pays",
			aditionalConsultContent_5: "Nous vous informerons des activités et événements afin que vous puissiez profiter au maximum de votre nouvelle vie.",
			aditionalConsultTitle_6: "Attention personnalisée lors de votre voyage et de votre déménagement",
			aditionalConsultContent_6: "Nous nous occupons des détails ! De la planification de votre voyage à l'installation dans votre nouvelle maison.",
			sectionTitle_5: "Il y a encore plus",
			sectionSubtitle_5: "Services supplémentaires pour votre confort",
			aditionalService_1: "Accueil et transfert depuis l'aéroport.",
			aditionalService_2: "Planification de votre voyage et de votre déménagement.",
			aditionalService_3: "Assistance aux services de nettoyage et d'entretien.",
			contactTitle: "Faites le premier pas vers votre nouvelle vie dès maintenant",
			contactActionButton: "Prendre rendez-vous",
			formPageLabel_1: "Informations personnelles",
			formPageLabel_2: "Détails du paiement",
			formTitle_1: "Informations de base",
			formTitle_2: "Indiquez-nous votre adresse e-mail",
			modalTitle: "Plan sélectionné",
			inputLabel_1: "Nom",
			inputPlaceholder_1: "Entrez votre nom",
			inputLabel_2: "Téléphone",
			inputPlaceholder_2: "Entrez votre numéro de téléphone",
			inputLabel_3: "Email",
			inputPlaceholder_3: "Adresse e-mail",
			inputLabel_4: "Pays",
			inputPlaceholder_4: "Sélectionnez votre pays",
			inputLabel_5: "Observation",
			inputPlaceholder_5: "Écrivez ici...",
			inputLabel_6: "Numéro de carte",
			inputPlaceholder_6: "Entrez votre numéro de carte",
			inputLabel_7: "Nom",
			inputPlaceholder_7: "Entrez votre nom",
			inputLabel_8: "Expire",
			inputPlaceholder_8: "Date d'expiration",
			inputLabel_9: "CVC",
			inputPlaceholder_9: "Entrez le code CVC",
			inputLabel_10: "Pays",
			inputPlaceholder_10: "Sélectionnez votre pays",
			inputLabel_11: "Province",
			inputPlaceholder_11: "Sélectionnez",
			inputLabel_12: "Code postal",
			inputPlaceholder_12: "Entrez le code postal",
			buttonAction_1: "Sortir",
			buttonAction_2: "Étape suivante",
			buttonAction_3: "Retour",
			buttonAction_4: "Adhésion",
			buttonAction_5: "Choisir un autre plan",
			priceLabel: "Sous-total",
			successMessageTitle: "Votre adhésion a été effectuée avec succès.",
			successMessageContent: "Veuillez vérifier votre boîte de réception.",
			errorMessageTitle: "Votre affiliation n'a pas pu être effectuée.",
			errorMessageContent: "Impossible de vérifier vos informations de paiement.",
			infoMessageTitle: "Nous vérifions votre paiement.",
			infoMessageContent: "Veuillez ne pas quitter cette page pendant que nous vérifions votre paiement.",
			errorFindAffiliate: "Cet e-mail n'est pas affilié",
			priceTotalLabel: "Total",
  			feeLabel: "Taxe",
			planDate: "Date limite",
  			plan: "Plan"

		},
		contact: {
			miniTitleHeader1: "Embarquez pour l'aventure",
			bigTitleHeader1: "Prenez rendez-vous dès maintenant !",
			formTitle1: "Choisissez un jour pour que nous puissions vous contacter",
			formTitle2: "Parlez-nous un peu de vous",
			formLabelName: "Nom complet",
			formPlaceholderName: "Entrez votre nom complet",
			formLabelSubject: "Sujet",
			formPlaceholderSubject: "Sélectionner",
			formLabelEmail: "Adresse e-mail",
			formPlaceholderEmail: "Ex. : example@email.com",
			formLabelMessage: "Message",
			formPlaceholderMessage: "Dites-nous pourquoi vous nous contactez",
			formActionButton: "Prendre rendez-vous",
			formSubjectList: [
				{
					"key": "job",
					"value": "Je veux travailler au Luxembourg"
				},
				{
					"key": "jobs",
					"value": "Je veux en savoir plus sur les emplois au Luxembourg"
				},
				{
					"key": "job_permit",
					"value": "Je souhaite des informations sur le permis de travail"
				},
				{
					"key": "business",
					"value": "Je veux créer une entreprise au Luxembourg"
				},
				{
					"key": "study",
					"value": "Je veux étudier au Luxembourg"
				},
				{
					"key": "languages",
					"value": "Je veux apprendre des langues au Luxembourg"
				},
				{
					"key": "stay",
					"value": "Je veux savoir où me loger au Luxembourg"
				},
				{
					"key": "investment",
					"value": "Je veux investir au Luxembourg"
				}
			  ],

			calendarTitle: "Sélectionnez une date",
			sectionTitle_1: "Planifiez avec nous !",
			sectionContent_1:
				"Vous souhaitez avoir une réunion avec Libling Solutions? Nous sommes à votre entière disposition pour vous fournir un service complet.",
			sectionTitle_2: "Nous te tiendrons toujours au courant de tout",
			sectionContent_2:
				"Parce que vous êtes notre priorité. Abonnez-vous à notre bulletin d'information pour être le premier à recevoir toutes nos nouveautés, actualités, produits et services.",
			form_name: "Noms",
			form_subject: "Objet",
			form_email: "E-mail",
			form_message: "Message",
			form_button: "Envoyer",
		},
		about: {
			headerTitle_1: "Lancez-vous dans l'aventure !",
			headerSubtitle_1: "Aspirez-vous à un nouveau départ au cœur de l'Europe ?",
			headerContent_1_1: "Libling Solutions",
			headerContent_1_2: " vous accompagne à chaque étape vers un avenir brillant au ",
			headerContent_1_3: "Luxembourg.",
			actionButton_1: "Découvrez ce que Libling vous offre",
			sectionTitle_1: "Apprenez à nous connaître",
			sectionSubtitle_1: "Qui sommes-nous ?",
			sectionContent_1_1: "Libling Solutions",
			sectionContent_1_2: " s'engage à transformer votre déménagement vers ",
			sectionContent_1_3: " Luxembourg ",
			sectionContent_1_4: " en une expérience positive. Notre équipe multilingue offre des conseils d'experts et un soutien personnalisé, s'occupant de tout, de la recherche de logement aux formalités d'immigration. Nous privilégions une communication claire et votre bien-être, garantissant un déménagement fluide et sans stress. Laissez-nous vous aider à faire du Luxembourg votre foyer en toute simplicité et en toute confiance.",

			actionButton_1_1: "En savoir plus",
			sectionTitle_2: "Professionnalisme",
			sectionSubtitle_2: "Innovateurs en déménagement et immobilier dans le Grand-Duché",
			sectionContent_2_1: "Chez ",
			sectionContent_2_2: "Libling Solutions",
			sectionContent_2_3: ", nous proposons des services complets pour répondre à tous vos besoins de déménagement et d'immobilier. Nous pensons que déménager dans une nouvelle maison doit être une expérience agréable et personnalisée, garantissant à vous et à votre famille une transition en douceur. Faites-nous confiance pour vous offrir l'excellence à chaque étape de votre processus de déménagement.",
			actionButton_2: "En savoir plus",
			sectionTitle_3: "Service d'excellence",
			sectionSubtitle_3: "Notre objectif est votre bien-être",
			sectionContent_3_1: "Libling Solutions",
			sectionContent_3_2: " a pour objectif de vous soutenir, de vous aider et de vous faciliter la tâche pour que votre déménagement au Grand-Duché soit agréable et confortable. Nous disposons d'une équipe de professionnels spécialisés dans chacun de vos besoins et dans votre langue. Notre priorité est de vous offrir un service de qualité.",
			actionButton_3: "En savoir plus",
			sectionTitle_4: "Contactez-nous",
			sectionSubtitle_4_1: "Commencez votre voyage vers le Luxembourg avec ",
			sectionSubtitle_4_2: "Libling Solutions",
			sectionContent_4: "Contactez notre équipe dès aujourd'hui et découvrez comment nous pouvons vous aider à créer un nouveau chez-vous.",
			actionButton_4: "Je veux prendre rendez-vous",
		  },		  
		mail: {
			main: "J'aimerais avoir plus d'informations sur Libling",
			subject_1: "Information",
			subject_2: "Services",
			subject_3: "Salutations",
			package: "Je suis intéressé par le pack suivant: ",
			date: "Bonjour, je souhaite un rendez-vous pour la journée :",
			notify: "Ton message a été envoyé avec succès",
			failed: "La demande n'a pas pu être complétée",

			infoContent1:"Merci de nous avoir contactés",
			infoContent2:". Nous avons bien reçu votre message et nous vous répondrons dans les meilleurs délais.",

			affiliateTitle: "Merci de rejoindre notre famille",
			affiliateTitleAdmin: "Un nouveau paiement d'affiliation a été enregistré",
			affiliateContent_1: "Bienvenue !",
			affiliateContent_2: "Chez Libling, nous sommes ravis que vous ayez rejoint notre programme d'affiliation.",
			affiliateContent_3: "Votre décision de faire partie de notre communauté nous remplit de joie et nous motive à continuer à offrir le meilleur service à ceux qui recherchent un nouveau départ au Luxembourg.",
			affiliateContent_4: "En tant qu'affilié, vous avez accès à des avantages exclusifs et à un soutien constant de notre équipe d'experts.",
			affiliateContent_5: "Ensemble, nous pouvons réaliser de grandes choses et aider de nombreuses personnes à réaliser leurs rêves !",
			contentBottom: "L'équipe Libling.",

			footerTopTitle: "Nous sommes là pour vous servir",
			footerTopText_1: "Avez-vous des questions ?",
			footerTopText_2: " Écrivez-nous à ",
			footerTopText_3: "info@libling.com",
			footerTopText_4: " et nous vous contacterons dans les plus brefs délais. Vous pouvez également nous laisser des commentaires sur nos services à l'adresse ",
			footerTopText_5: "info@libling.lu",
			footerBottomText_1: "Conditions générales",
			footerBottomText_2: "Confidentialité",
			footerBottomText_3: "Contactez-nous",
			footerBottomText_4: "Se désabonner",
		},
	},
}
