export const dict = {
	es: {
		adminProperties: {
			indexTitle: "Inmuebles registrados",
			indexEmptyListTitle: "Aún no has registrado tus inmuebles",
			indexEmptyListDescription:
				"Puedes registrar y gestionar tus inmuebles desde aquí.",
			createTitle: "Nueva propiedad",
			formLabelCountry: "Pais",
			formLabelCurrency: "Moneda",
			formLabelOptional: "Opcional",
			formLabelTitle: "Título",
			formLabelDescription: "Descripción",
			formLabelAddress: "Dirección",
			formLabelFurnished: "¿Está amoblado?",
			formLabelArea: "Área",
			formLabelBedrooms: "Número de dormitorios",
			formLabelBathrooms: "Número de baños",
			formLabelHeatingType: "Tipo de calefacción",
			formLabelHeatingMedium: "Medio de calefacción",
			formLabelHeatingEnergy: "Energía de calefacción",
			formLabelSale: "Venta",
			formLabelRent: "Alquiler",
			formLabelView: "Vista",
			formLabelPropertyType: "Tipo de propiedad",
			formLabelFrecuency: "Frecuencia de pago",
			formLabelPrice: "Precio",
			formLabelSufaces: "Superficies",
			formLabelBenefits: "Beneficios",
			formLabelNearPlaces: "Lugares cercanos",
			formLabelLegalNotes: "Noticias legales",
			formLabelTumbnail: "Portada",
			formLabelImages: "Imagenes",
			formLabelPhotos: "Sube fotos del inmueble",
			formLabelPhotosDescription:
				"Una vez cargadas, selecciona la imagen que quieras como portada.",
			formLabelPhotosAdvertise:
				"Las imágenes deben tener un peso menor a 2MB cada una.",
			formLabelMap: "Indica en el mapa la ubicación del inmueble",
			formLinkEdit: "Editar",
			formButtonPreview: "Vista previa",
			formButtonReturn: "Volver",
			formButtonRegister: "Registrar",
			formButtonBack: "Atrás",
			formButtonNext: "Siguiente",
			formButtonAddPhoto: "Agregar fotos",
			formButtonAddSurfaces: "Agregar superficie",
			formButtonAddBenefits: "Agregar beneficio",
			formButtonAddNearPlaces: "Agregar lugar cercano",
			formButtonAddLegalNotes: "Agregar nota legal",
			formOptionYes: "Sí",
			formOptionNo: "No",
			formOptionCancel: "Cancelar registro",
			formPlaceholderSelect: "Selecciona",
			formPlaceholderSelectText: "Selecciona o escribe...",
			formPlaceholderSelectAdd: "Agregar",
			formPlaceholderText: "Escribe aquí...",
			formPlaceholderView:
				"Ejemplo: panorámica, parcial, cerrada, vista al mar...",
			formPlaceholderSurfaces_1: "Cantidad",
			formPlaceholderSurfaces_2: "Descripción",
			formPlaceholderSurfaces_3: "Área",
			formPlaceholderBenefits: "Ejemplo: terraza, jardín, balcón...",
			formPlaceholderNearPlaces: "Ejemplo: supermercado, gimnasio, parque...",
			formPlaceholderLegalNotes:
				"Ejemplo: honorarios del propietario, consumo energético clase G...",
			formStepTitle_1: "Describe el inmueble",
			formStepTitle_2: "Detalla el espacio",
			formStepTitle_3: "Destaca las ventajas del inmueble",
			formStepTitle_4: "Agrega un título, descripción e imágenes",
			formStepTitle_5: "Establece las condiciones de pago",
			formPreviewTitle: "Revisa el inmueble antes de registrarto",
			formConfirmTitle: "Confirma la creación del nuevo inmueble",
			formConfirmOption: "Publicar inmueble",
			formStep: "Paso",
			formStepConnector: "de",
			formValidationRequired: "Este campo es requerido",
			formValidationNumbers: "Este campo solo acepta números",
			formValidationLetters: "Este campo solo acepta letras",
			formValidationPhotos: "Debe agregar como mínimo una imagen",
			previewSectionTitle_1: "Descripción del inmueble",
			previewSectionTitle_2: "Detalles del espacio",
			previewSectionTitle_3: "Ventajas del inmueble",
			previewSectionTitle_4: "Título, descripción e imágenes",
			previewSectionTitle_5: "Condiciones de pago",
			modalCreateTitle: "Confirma la creación del nuevo inmueble",
			modalCreateOption: "Publicar inmueble.",
			modalPublishConfirm: "Confirma la publicación del inmueble",
			modalPauseConfirm: "Confirma la pausa de la publicación",
			modalDeleteTitle: "Si eliminas el inmueble ya no podrás recuperarlo.",
			modalDeletePauseTitle:
				"Si eliminas el inmueble ya no podrás recuperarlo.",
			modalDeleteText:
				"Puedes pausar la publicación para conservarlo y reactivarla más tarde.",
			modalDeleteButton: "Eliminar",
			toastDelete: "El inmueble fue eliminado con éxito.",
			toastPublish: "El inmueble fue publicado con éxito.",
			toastPause: "La publicación fue pausada con éxito.",
			actionPublish: "Publicar",
			actionPause: "Pausar",
			actionDetail: "Ver detalle",
			actionPreview: "Vista previa",
		},
		adminNav: {
			propertiesTitle: "Inmuebles",
			dashboardTitle: "Inicio",
			closeSession: "Cerrar sesión",
		},
		auth: {
			login_title: "Vamos a ingresar a tu cuenta",
			login_subtitle: "Por favor, ingresa tus datos",
			change_password_title: "Cambiar contraseña",
			change_password_subtitle:
				"A continuación, ingresa tu nueva contraseña para restablecerla",
			login_email: "Correo electrónico",
			login_password: "Contraseña",
			login_password_confirm: "Repetir contraseña",
			login_forgot: "¿Olvidaste tu contraseña?",
			login_button: "Iniciar sesión",
			login_remember: "Recuérdame",
			login_placeholder: "Escribe aqui...",
			login_email_required: "El correo es requerido",
			login_password_required: "La contraseña es requerida",
			login_password_confirmation_required: "Las contraseñas no coninciden",
			forgot_password_title: "Recuperar contraseña",
			forgot_password_subtitle:
				"Ingresa el correo electrónico que usaste al registrarte. Recibirás un enlace para restablecer tu contraseña.",
			email_not_found_title: "Correo electrónico no registrado",
			email_not_found_subtitle:
				"Parece que no encontramos una cuenta asociada a tu correo electrónico. Asegúrate de haber introducido la dirección correcta y vuelve a intentarlo.",
			email_send_title: "Correo electrónico enviado",
			email_send_subtitle:
				"Ingresa al enlace enviado a tu correo electrónico para restablecer tu contraseña.",
			email_send_required: "El correo electrónico es requerido",
			email_send_validation: "El campo debe ser un correo electrónico",
			email_set_title: "Contraseña restablecida",
			email_set_subtitle: "Ahora puedes continuar a tu entorno de trabajo.",
			formButtonContinue: "Continuar",
			formButtonSendLink: "Enviar enlace",
			formButtonReturn: "Volver",
			formButtonChangePassword: "Cambiar contraseña",
			formButtonOrLogin: "O inicia sesión",
			error_credentials: "Las credenciales no son correctas",
			error_default: "Ha ocurrido un error",
		},
		navbar: {
			link_1: "Quienes somos",
			link_2: "Inicio",
			link_3: "Servicios",
			link_4: "Contáctanos",
			admin_1: "Propiedades",
		},
		footer: {
			title_1: "Contacto",
			title_2: "Deja tu correo y te contactaremos",
			title_3: "Síguenos",
		},
		home: {
			sectionButton_1: "Agendar",
			sectionButton_2: "Ver más",
			titleHeader_1: "Con Libling solutions su",
			titleHeader_2: "instalación en Luxemburgo",
			titleHeader_3: "es fácil y segura.",
			subtitleHeader_1: "",
			subtitleHeader_2: "",
			sectionTitle_1: "Estamos a su lado para ayudarle en todo lo que necesite",
			sectionContent_1:
				"Brindándole un servicio completo y apoyo óptimo en su proceso de instalación en Luxemburgo 🇱🇺",
			sectionTitle_2: "Juntos podremos lograrlo",
			sectionContent_2:
				"Empezar en un país distinto a veces puede ser retador, pero no se preocupe estamos con usted para facilitarle los procesos administrativos y pueda integrarse rápidamente en la comunidad luxemburguesa.",
			sectionTitle_3: "Nuestros servicios:",
			sectionList_3: [
				"Visitar o  instalarse en el gran ducado",
				"Busqueda o venta/compra de un bien inmobiliario",
				"Asesoramiento personalizado",
				"Tours y puntos de interes",
			],
			sectionTitle_4: "Le ayudamos a gestionar y le asesoramos",
			sectionList_4: [
				"Solicitud de permiso de trabajo/autorización temporal.",
				"Búsqueda de su casa, apartamento.",
				"Busqueda de escuela y guardería para sus hijos.",
				"Mercado inmobiliario, servicio de compra-venta, alquiler y gestión de propiedades.",
				"Asoramiento de bienes inmuebles.",
				"Organización de la mudanza.",
			],
			reviewName_1: "MARIA SMITH",
			reviewDescription_1:
				"Hace 1 mes que vivo en Luxemburgo gracias a Libling. Pude encontrar un trabajo en el sector de tecnología, que es donde mejor me especializo. También me ayudaron sobre cómo abrir una cuenta bancaria, solicitud de permiso de residencia y como hacer amigos en Luxemburgo.",
			reviewName_2: "LUIS MORENO",
			reviewDescription_2:
				"Mi  nombre es Luis Moreno y soy de Peru. Mi novia y yo decidimos irnos a Luxemburgo buscando un mejor futuro para ambos hace un año, solicitamos la ayuda de Libling y definitivamente una de las mejores decisiones que pudimos tomar.",
			reviewName_3: "LAURA MARTINEZ",
			reviewDescription_3:
				"Hola, soy Laura de Mexico. Luxemburgo para mí siempre ha sido una ciudad magnífica y con grandes oportunidades, así que contacté a Libling para tener los requisitos necesarios para poder vivir allí. Los recomiendo al 100%",
		},
		services: {
			aditionalTitle_1: "Tenemos más para usted",
			aditionalService_1: "Organización de recogida en el aeropuerto",
			aditionalService_2:
				"Planificamos y organizamos su viaje y mudanza a Luxemburgo 🇱🇺",
			aditionalService_3: "Asistencia en servicios de limpieza y mantenimiento",
			aditionalService_4:
				"Asistencia de soporte después de la mudanza (1 mes vía teléfono).",
			sectionTitle_1: "Le acompañamos desde el día 1",
			sectionContent_1:
				"Desde su llegada al aeropuerto, hasta hacer un tour por la ciudad de Luxemburgo, Libling estará allí para usted, brindándole toda la información y en su idioma nativo.",
			sectionTitle_2: "Paquetes para todos",
			cardTitle_1: "Básico",
			cardList_1: [
				"Asistencia ligera",
				"Trámites administrativos - Inscripción",
				"Inscripción + 4 servicios",
				"1 día de asistencia",
			],
			cardTitle_2: "Estándar",
			cardList_2: [
				"Asistencia estándar",
				"Trámite administrativos - Inscripción + 4 servicios",
				"Búsqueda de casa + acompañamiento",
				"Búsqueda de colegio",
				"2 días de asistencia",
			],
			cardTitle_3: "Premium",
			cardList_3: [
				"Asistencia completa",
				"Trámites administrativos - Inscripción + 4 servicios",
				"Búsqueda de casa acompañamiento durante el proceso de buscaqueda",
				"Búsqueda de colegio / guardería",
				"Alojamiento a corto plazo",
				"Organización de recogida en el aeropuerto",
				"Tour de orientación",
				"3 días de asistencia",
			],
			cardTitle_4: "Lista de servicios y consultorías adicionales",
			cardList_4: [
				"Contamos con un equipo completo que forman parte de Libling Solutions y estan a su disposicion:",
				"Consultoría inmobiliaria / vivienda",
				"Consultoría de arquitectura / construcción / inversión",
				"Consultoría jurídica",
				"Consultorias médicas",
				"Vida social/eventos sociales y culturales",
				"Organización y planificación personalizada de su viaje y mudanza",
			],
			cardDescription_4: "Servicio de orientación y consultoría básica",
			cardActionText: "Solicitar",
			sectionTitle_3: "¡La educación en Luxemburgo es GRATIS!",
			sectionContent_3:
				"La educación de los pequeños es de gran importancia y Libling le ayudará a encontrar las escuelas/colegios y guarderías que sean de agrado para su familia.",
			sectionTitle_4: "Le ayudamos con sus tramites administrativos",
			sectionContent_4:
				"Durante su llegada a Luxemburgo Libling tendrá todo a la mano para usted y su familia. Esto incluye hospedaje temporal y servicios de traslado y una guía de instalación y asistencia telefónica.",
			sectionTitle_5: "Agende su cita",
			sectionContent_5:
				"Si desea tener una reunión con nosotros, puede revisar nuestro calendario haciendo click en el botón de agendar para visualizar la disponibilidad y así darle la atención y servicio que usted merece.",
			sectionButton_5: "Agendar",
		},
		contact: {
			calendarTitle: "Selecciona una fecha",
			sectionTitle_1: "¡Agende con nosotros!",
			sectionContent_1:
				"Desea tener una reunión con Libling solutions. Estamos a su entera disposición, para darle un servicio integral.",
			sectionTitle_2: "Le mantendremos siempre al corriente de todo",
			sectionContent_2:
				"Porque usted es nuestra prioridad. Inscríbase a nuestro boletín informativo para que sea el primero en recibir todas nuestras novedades, noticias, productos y servicios.",
			form_name: "Nombres",
			form_subject: "Asunto",
			form_email: "Correo electrónico",
			form_message: "Mensaje",
			form_button: "Enviar",
		},
		about: {
			titleHeader_1: "Compartimos",
			titleHeader_2: "nuestra historia",
			titleHeader_3: "contigo",
			sectionTitle_1: "¿Quiénes somos?",
			sectionContent_1:
				"Libling Solutions es la primera empresa hispanoamericana de reubicación e inmobiliaria en el Gran Ducado de Luxemburgo. Fue creada y está dirigida por Madame Lidiz Cruz, luxemburguesa y hondureña, quien cree firmemente que con la información y la guía de excelencia podrá tener éxito en su mudanza e integración en Luxemburgo.",
			sectionTitle_2:
				"Innovadores en relocalización y agencia inmobiliaria en el gran ducado",
			sectionContent_2:
				"En Libling Solutions encontrara todo lo que usted necesita, creemos que la reubicación debe ser grata y personalizada, garantizándole a usted y su familia un proceso de reubicación de excelencia.",
			sectionTitle_3: "Nuestro objetivo es su bienestar",
			sectionContent_3:
				"Libling Solutions tiene como objetivo apoyarle, ayudarle y facilitarle todo para que su mudanza al Gran Ducado sea placentera y cómoda. Contamos con un equipo de profesionales especializados en cada una de sus necesidades y en su idioma. Nuestra prioridad es brindarle un servicio de calidad.",
		},
		mail: {
			main: "Quiero obtener más información acerca de libling",
			subject_1: "Información",
			subject_2: "Servicios",
			package: "Estoy interesado en el siguiente paquete: ",
			date: "Hola quisiera una cita para el día: ",
			notify: "Su mensaje ha sido enviado con éxito",
			failed: "No se ha podido completar la solicitud",
		},
	},
	en: {
		adminProperties: {
			indexTitle: "Registered properties",
			indexEmptyListTitle: "You have not registered your properties yet",
			indexEmptyListDescription:
				"You can register and manage your properties from here.",
			createTitle: "New property",
			formLabelCountry: "Country",
			formLabelCurrency: "Currency",
			formLabelOptional: "Optional",
			formLabelTitle: "Title",
			formLabelDescription: "Description",
			formLabelAddress: "Address",
			formLabelFurnished: "Is it furnished?",
			formLabelArea: "Area",
			formLabelBedrooms: "Number of bedrooms",
			formLabelBathrooms: "Number of bathrooms",
			formLabelHeatingType: "Heating type",
			formLabelHeatingMedium: "Heating fuel",
			formLabelHeatingEnergy: "Heating energy",
			formLabelSale: "Sale",
			formLabelRent: "Rent",
			formLabelView: "View",
			formLabelPropertyType: "Property type",
			formLabelFrecuency: "Payment frequency",
			formLabelPrice: "Price",
			formLabelSufaces: "Surfaces",
			formLabelBenefits: "Benefits",
			formLabelNearPlaces: "Nearby places",
			formLabelLegalNotes: "Legal notes",
			formLabelTumbnail: "Thumbnail",
			formLabelImages: "Images",
			formLabelPhotos: "Upload photos of the property",
			formLabelPhotosDescription:
				"Once uploaded, select the image you want to use as a cover.",
			formLabelPhotosAdvertise: "Images must be less than 2MB each.",
			formLabelMap: "Indicate the location of the property on the map.",
			formLinkEdit: "Edit",
			formButtonPreview: "Preview",
			formButtonReturn: "Return",
			formButtonRegister: "Register",
			formButtonBack: "Back",
			formButtonNext: "Next",
			formButtonAddPhoto: "Add photos",
			formButtonAddSurfaces: "Add surface",
			formButtonAddBenefits: "Add benefit",
			formButtonAddNearPlaces: "Add nearby place",
			formButtonAddLegalNotes: "Add legal note",
			formOptionYes: "Yes",
			formOptionNo: "No",
			formOptionCancel: "Cancel registration",
			formPlaceholderSelect: "Select",
			formPlaceholderSelectText: "Select or type...",
			formPlaceholderSelectAdd: "Add",
			formPlaceholderText: "Type here...",
			formPlaceholderView: "Example: panoramic, partial, closed, sea view...",
			formPlaceholderSurfaces_1: "Quantity",
			formPlaceholderSurfaces_2: "Description",
			formPlaceholderSurfaces_3: "Area",
			formPlaceholderBenefits: "Example: terrace, garden, balcony...",
			formPlaceholderNearPlaces: "Example: supermarket, gym, park...",
			formPlaceholderLegalNotes:
				"Example: owner's fees, energy consumption class G...",
			formStepTitle_1: "Describe the property",
			formStepTitle_2: "Detail the space",
			formStepTitle_3: "Highlight the advantages of the property",
			formStepTitle_4: "Add a title, description and images",
			formStepTitle_5: "Set payment terms",
			formPreviewTitle: "Review the property before registering",
			formConfirmTitle: "Confirm the creation of the new property",
			formConfirmOption: "Publish property",
			formStep: "Step",
			formStepConnector: "of",
			formValidationRequired: "This field is required",
			formValidationNumbers: "This field only accepts numbers",
			formValidationLetters: "This field only accepts letters",
			formValidationPhotos: "You must add at least one image.",
			previewSectionTitle_1: "Property Description",
			previewSectionTitle_2: "Space Details",
			previewSectionTitle_3: "Property Advantages",
			previewSectionTitle_4: "Title, Description and Images",
			previewSectionTitle_5: "Payment Terms",
			modalCreateTitle: "Confirm New Property Creation",
			modalCreateOption: "Publish Property.",
			modalPublishConfirm: "Confirm Property Publication",
			modalPauseConfirm: "Confirm Publication Pause",
			modalDeleteTitle:
				"If you delete the property, you will not be able to recover it.",
			modalDeletePauseTitle:
				"If you delete the property, you will not be able to recover it.",
			modalDeleteText:
				"You can pause the publication to keep it and reactivate it later.",
			modalDeleteButton: "Delete",
			toastDelete: "Property successfully deleted.",
			toastPublish: "Property successfully published.",
			toastPause: "Publication successfully paused.",
			actionPublish: "Publish",
			actionPause: "Pause",
			actionDetail: "View Details",
			actionPreview: "Preview",
		},
		adminNav: {
			propertiesTitle: "Real estate",
			dashboardTitle: "Home",
			closeSession: "Close session",
		},
		auth: {
			login_title: "Let's log in to your account",
			login_subtitle: "Please enter your data",
			change_password_title: "Change password",
			change_password_subtitle: "Then enter your new password to reset it",
			login_email: "Email",
			login_password: "Password",
			login_password_confirm: "Confirm password",
			login_forgot: "Forgot your password?",
			login_button: "Login",
			login_remember: "Remember me",
			login_placeholder: "Type here...",
			login_email_required: "Email is required",
			login_password_required: "Password is required",
			login_password_confirmation_required: "Passwords do not match",
			forgot_password_title: "Recover password",
			forgot_password_subtitle:
				"Enter the email address you used to register. You will receive a link to reset your password.",
			email_not_found_title: "Email not registered",
			email_not_found_subtitle:
				"We can't seem to find an account associated with your email. Please make sure you entered the correct address and try again.",
			email_send_title: "Email sent",
			email_send_subtitle:
				" Enter the link sent to your email to reset your password.",
			email_send_required: "The email is required",
			email_send_validation: "The field must be an email",
			email_set_title: "Password reset",
			email_set_subtitle: "You can now continue to your work environment.",
			formButtonContinue: "Continue",
			formButtonSendLink: "Send link",
			formButtonReturn: "Return",
			formButtonChangePassword: "Change password",
			formButtonOrLogin: "Or log in",
			error_credentials: "The credentials are not correct",
			error_default: "An error has occurred",
		},
		navbar: {
			link_1: "About us",
			link_2: "Home",
			link_3: "Services",
			link_4: "Contact",
			admin_1: "Properties",
		},
		footer: {
			title_1: "Contact",
			title_2: "Leave your email, and we will contact you",
			title_3: "Follow us",
		},
		home: {
			sectionButton_1: "Schedule",
			sectionButton_2: "See more",
			titleHeader_1: "With Libling Solutions, ",
			titleHeader_2: "your relocation to Luxembourg ",
			titleHeader_3: "is easy and secure.",
			subtitleHeader_1: " ",
			subtitleHeader_2: " ",
			sectionTitle_1:
				"We are by your side to assist you with whatever you need",
			sectionContent_1:
				"Providing you with comprehensive service and optimal support in your relocation process to Luxembourg 🇱🇺.",
			sectionTitle_2: "Together, we can achieve it",
			sectionContent_2:
				"Starting in a different country can sometimes be challenging, but don't worry; we are with you to simplify administrative processes and help you integrate quickly into the Luxembourgish community.",
			sectionTitle_3: "Our services :",
			sectionList_3: [
				"Visit or settle in the Grand Duchy",
				"Search or buy/sell real estate",
				"Personalized advice",
				"Tours and points of interest",
			],
			sectionTitle_4: "We help you manage and advise you",
			sectionList_4: [
				"Work permit application/temporary authorization.",
				"Search for a house or apartment.",
				"Search for a school and daycare for your children.",
				"Real estate market, buying and selling services, rental and property management.",
				"Real estate advice.",
				"Organisation of the move.",
			],
			reviewName_1: "MARIA SMITH",
			reviewDescription_1:
				"'I have been living in Luxembourg for 1 month thanks to Libling. I found a job in the technology sector, where I specialize the most. They also helped me with opening a bank account, residence permit application, and making friends in Luxembourg.'",
			reviewName_2: "LUIS MORENO",
			reviewDescription_2:
				"'My name is Luis Moreno, and I am from Peru. My girlfriend and I decided to move to Luxembourg in search of a better future for both of us a year ago. We sought the assistance of Libling, and it was definitely one of the best decisions we could have made.'",
			reviewName_3: "LAURA MARTINEZ",
			reviewDescription_3:
				"'Hello, I'm Laura from Mexico. Luxembourg has always been a magnificent city with great opportunities for me, so I contacted Libling to get the necessary requirements to live there. I recommend them 100%.'",
		},
		services: {
			aditionalTitle_1: "We have more for you",
			aditionalService_1: "Airport pickup arrangement",
			aditionalService_2:
				"We plan and organize your trip and move to Luxembourg 🇱🇺",
			aditionalService_3: "Assistance in cleaning and maintenance services",
			aditionalService_4:
				"Support assistance after the move (1 month via phone).",
			sectionTitle_1: "We accompany you from day one",
			sectionContent_1:
				"From your arrival at the airport to taking a tour of the city of Luxembourg, Libling will be there for you, providing you with all the information in your native language.",
			sectionTitle_2: "Packages for everyone",
			cardTitle_1: "Basic",
			cardList_1: [
				"Light assistance",
				"Administrative procedures - Registration",
				"Registration + 4 services",
				"1 day of assitance",
			],
			cardTitle_2: "Standard",
			cardList_2: [
				"Standard assistance",
				"Administrative procedures - Registration + 4 services",
				"House search + support",
				"School search",
				"2 days of assistance",
			],
			cardTitle_3: "Premium",
			cardList_3: [
				"Full assistance",
				"Administrative procedures - Registration + 4 services",
				"House search with support throughout the search process",
				"School/nursery search",
				"Short-term accommodation",
				"Airport pickup organization",
				"Orientation tour",
				"3 days of assistance",
			],
			cardTitle_4: "List of additional services and consultantions",
			cardList_4: [
				"We have a complete team that are part of Libling Solutions and are at your disposal:",
				"Real estate consulting / housing",
				"Consulting architecture / construction / investment advice",
				"Legal consulting",
				"Medical consulting",
				"Social life/social and cultural events",
				"Personalized organization and planning of your trip and move",
			],
			cardDescription_4: "Guidance and consulting services",
			cardActionText: "Request",
			sectionTitle_3: "Education in Luxembourg is FREE!",
			sectionContent_3:
				"The education of the little ones is of great importance, and Libling will help you find schools/colleges and nurseries that suit your family.",
			sectionTitle_4: "We help you with your administrative procedures",
			sectionContent_4:
				"During your arrival in Luxembourg, Libling will have everything at hand for you and your family. This includes temporary accommodation and transfer services, an installation guide, and telephone assistance.",
			sectionTitle_5: "Schedule your appointment",
			sectionContent_5:
				"If you want to have a meeting with us, you can check our calendar by clicking the schedule button to view availability and provide the attention and service you deserve.",
			sectionButton_5: "Book an appointment",
		},
		contact: {
			calendarTitle: "Select a date",
			sectionTitle_1: "Schedule with us !",
			sectionContent_1:
				"Do you want to have a meeting with Libling Solutions? We are at your complete disposal to provide you with comprehensive service.",
			sectionTitle_2: "We will always keep you informed of everything",
			sectionContent_2:
				"Because you are our priority. Subscribe to our newsletter to be the first to receive all our updates, news, products, and services.",
			form_name: "Names",
			form_subject: "Subject",
			form_email: "E-mail",
			form_message: "Message",
			form_button: "Send",
		},
		about: {
			titleHeader_1: "We share",
			titleHeader_2: "our story",
			titleHeader_3: "with you",
			sectionTitle_1: " Who are we ?",
			sectionContent_1:
				"Libling Solutions is the first Spanish-American relocation/moving and real estate company in the Grand Duchy of Luxembourg. It was founded and is managed by Mrs. Lidiz Cruz, Luxembourgish and Honduran. She firmly believes that with information and excellent guidance, you can succeed in your move and integration in Luxembourg.",
			sectionTitle_2:
				"Innovators in Relocation and Real Estate in the Grand Duchy",
			sectionContent_2:
				"At Libling Solutions, you will find everything you need. We believe that relocation should be pleasant and personalized, guaranteeing you and your family an excellent moving process.",
			sectionTitle_3: "Our Goal is Your Well-being",
			sectionContent_3:
				"Libling Solutions aims to support, assist, and facilitate everything for your move to the Grand Duchy to be pleasant and comfortable. We have a team of professionals specialized in each of your needs and in your language. Our priority is to provide you with quality service.",
		},
		mail: {
			main: "I would like to know more about Libling",
			subject_1: "Information",
			subject_2: "Services",
			package: "I am interested by the following pack: ",
			date: "Hello, I would like an appointment for the day: ",
			notify: "Your message was sent with success",
			failed: "Your request could not be completed",
		},
	},
	fr: {
		adminProperties: {
			indexTitle: "Propriétés enregistrées",
			indexEmptyListTitle: "Vous n'avez pas encore enregistré vos propriétés",
			indexEmptyListDescription:
				"Vous pouvez enregistrer et gérer vos propriétés à partir d'ici.",
			createTitle: "Nouvelle propriété",
			formLabelCountry: "Pays",
			formLabelCurrency: "Devise",
			formLabelOptional: "Optionnel",
			formLabelTitle: "Titre",
			formLabelDescription: "Description",
			formLabelAddress: "Adresse",
			formLabelFurnished: "Est-il meublé ?",
			formLabelArea: "Superficie",
			formLabelBedrooms: "Nombre de chambres",
			formLabelBathrooms: "Nombre de salles de bain",
			formLabelHeatingType: "Type de chauffage",
			formLabelHeatingMedium: "Combustible de chauffage",
			formLabelHeatingEnergy: "Énergie de chauffage",
			formLabelSale: "Vente",
			formLabelRent: "Loyer",
			formLabelView: "Vue",
			formLabelPropertyType: "Type de bien",
			formLabelFrecuency: "Fréquence de paiement",
			formLabelPrice: "Prix",
			formLabelSufaces: "Surfaces",
			formLabelBenefits: "Avantages",
			formLabelNearPlaces: "Lieux à proximité",
			formLabelLegalNotes: "Notes légales",
			formLabelTumbnail: "Vignette",
			formLabelImages: "Images",
			formLabelPhotos: "Téléchargez des photos du bien",
			formLabelPhotosDescription:
				"Une fois chargées, sélectionnez l'image que vous souhaitez utiliser comme couverture.",
			formLabelPhotosAdvertise:
				"Les images doivent peser moins de 2 Mo chacune.",
			formLabelMap: "Indiquez l'emplacement de la propriété sur la carte.",
			formLinkEdit: "Modifier",
			formButtonPreview: "Aperçu",
			formButtonReturn: "Retour",
			formButtonRegister: "Enregistrer",
			formButtonBack: "Précédent",
			formButtonNext: "Suivant",
			formButtonAddPhoto: "Ajouter des photos",
			formButtonAddSurfaces: "Ajouter une surface",
			formButtonAddBenefits: "Ajouter un avantage",
			formButtonAddNearPlaces: "Ajouter un lieu à proximité",
			formButtonAddLegalNotes: "Ajouter une note légale",
			formOptionYes: "Oui",
			formOptionNo: "Non",
			formOptionCancel: "Annuler l'enregistrement",
			formPlaceholderSelect: "Sélectionner",
			formPlaceholderSelectText: "Sélectionnez ou tapez...",
			formPlaceholderSelectAdd: "Ajouter",
			formPlaceholderText: "Tapez ici...",
			formPlaceholderView: "Exemple: panoramique, partiel, fermé, vue mer...",
			formPlaceholderSurfaces_1: "Quantité",
			formPlaceholderSurfaces_2: "Description",
			formPlaceholderSurfaces_3: "Superficie",
			formPlaceholderBenefits: "Exemple: terrasse, jardin, balcon...",
			formPlaceholderNearPlaces: "Exemple: supermarché, gymnase, parc...",
			formPlaceholderLegalNotes:
				"Exemple: frais de propriétaire, consommation énergétique classe G...",
			formStepTitle_1: "Décrivez la propriété",
			formStepTitle_2: "Détaillez l'espace",
			formStepTitle_3: "Mettez en valeur les avantages de la propriété",
			formStepTitle_4: "Ajoutez un titre, une description et des images",
			formStepTitle_5: "Définir les conditions de paiement",
			formPreviewTitle: "Vérifiez la propriété avant de vous inscrire",
			formConfirmTitle: "Confirmer la création de la nouvelle propriété",
			formConfirmOption: "Publier la propriété",
			formStep: "Étape",
			formStepConnector: "de",
			formValidationRequired: "Ce champ est obligatoire",
			formValidationNumbers: "Ce champ n'accepte que des chiffres",
			formValidationLetters: "Ce champ n'accepte que des lettres",
			formValidationPhotos: "Vous devez ajouter au moins une image.",
			previewSectionTitle_1: "Description du bien",
			previewSectionTitle_2: "Détails de l'espace",
			previewSectionTitle_3: "Avantages du bien",
			previewSectionTitle_4: "Titre, description et images",
			previewSectionTitle_5: "Conditions de paiement",
			modalCreateTitle: "Confirmer la création d'un nouveau bien",
			modalCreateOption: "Publier un bien.",
			modalPublishConfirm: "Confirmer la publication du bien",
			modalPauseConfirm: "Confirmer la pause de la publication",
			modalDeleteTitle:
				"Si vous supprimez le bien, vous ne pourrez plus le récupérer.",
			modalDeletePauseTitle:
				"Si vous supprimez le bien, vous ne pourrez plus le récupérer.",
			modalDeleteText:
				"Vous pouvez suspendre la publication pour la conserver et la réactiver ultérieurement.",
			modalDeleteButton: "Supprimer",
			toastDelete: "Le bien a été supprimé avec succès.",
			toastPublish: "Le bien a été publié avec succès.",
			toastPause: "La publication a été suspendue avec succès.",
			actionPublish: "Publier",
			actionPause: "Suspendre",
			actionDetail: "Voir les détails",
			actionPreview: "Aperçu",
		},

		adminNav: {
			propertiesTitle: "Immobilier",
			dashboardTitle: "Home",
			closeSession: "Fermer la session",
		},
		auth: {
			login_title: "Nous allons nous connecter à votre compte",
			login_subtitle: "Veuillez saisir vos coordonnées",
			change_password_title: "Modifier le mot de passe",
			change_password_subtitle:
				"Saisissez ensuite votre nouveau mot de passe pour le réinitialiser",
			login_email: "E-mail",
			login_password: "Mot de passe",
			login_password_confirm: "Répéter le mot de passe",
			login_forgot: "Vous avez oublié votre mot de passe?",
			login_button: "Se connecter",
			login_remember: "Souvenez-vous de moi",
			login_placeholder: "Tapez ici...",
			login_email_required: "Le courrier est obligatoire",
			login_password_required: "Le mot de passe est requis",
			login_password_confirmation_required:
				"les mots de passe ne correspondent pas",
			forgot_password_title: "Récupérer le mot de passe",
			forgot_password_subtitle:
				"Entrez l'adresse électronique que vous avez utilisée pour vous inscrire. Vous recevrez un lien pour réinitialiser votre mot de passe",
			email_not_found_title: "Email non enregistré",
			email_not_found_subtitle:
				"Nous ne parvenons pas à trouver un compte associé à votre adresse électronique. Veuillez vous assurer que vous avez saisi l'adresse correcte et réessayez",
			email_send_title: "Email envoyé",
			email_send_subtitle:
				"Saisissez le lien envoyé à votre adresse électronique pour réinitialiser votre mot de passe",
			email_send_required: "L'email est obligatoire",
			email_send_validation: "Le champ doit être un courriel",
			email_set_title: "Réinitialisation du mot de passe",
			email_set_subtitle: "Vous pouvez maintenant continuer à travailler",
			formButtonContinue: "Continuer",
			formButtonSendLink: "Envoyer le lien",
			formButtonReturn: "Retour",
			formButtonChangePassword: "Modifier le mot de passe",
			formButtonOrLogin: "Ou se connecter",
			error_credentials:
				"Les informations d'identification ne sont pas correctes",
			error_default: "Une erreur s'est produite",
		},
		navbar: {
			link_1: "A propos de nous",
			link_2: "Accueil",
			link_3: "Services",
			link_4: "Contact",
			admin_1: "Propriétés",
		},
		footer: {
			title_1: "Contact",
			title_2: "Laissez nous votre e-mail et nous vous recontacterons",
			title_3: "Suivez-nous",
		},
		home: {
			sectionButton_1: "Planifier",
			sectionButton_2: "Voir plus",
			titleHeader_1: "Avec Libling Solutions,",
			titleHeader_2: "votre installation au Luxembourg",
			titleHeader_3: "est facile et sécurisée.",
			subtitleHeader_1: " ",
			subtitleHeader_2: " ",
			sectionTitle_1:
				"Nous sommes à vos côtés pour vous aider en tout ce dont vous avez besoin",
			sectionContent_1:
				"En vous fournissant un service complet et un soutien optimal dans votre processus d'installation au Luxembourg 🇱🇺",
			sectionTitle_2: "Ensemble, nous pouvons y arriver",
			sectionContent_2:
				"Tout recommencer dans un pays différent peut parfois être un défi, mais ne vous inquiètez pas. Nous serons à vos côtés pour faciliter vos processus administratifs, légaux et culturels afin que vous puissiez vous adapter rapidement à la communauté luxembourgeoise.",
			sectionTitle_3: "Nos services :",
			sectionList_3: [
				"Visiter ou s'installer dans le Grand-Duché",
				"Recherche ou achat/vente de biens immobiliers",
				"Conseils personnalisés",
				"Visites et points d'intérêt",
			],
			sectionTitle_4: "Nous vous aidons à gérer et nous vous conseillons",
			sectionList_4: [
				"Demande de permis de travail/autorisation temporaire.",
				"Recherche de maison ou d'appartement.",
				"Recherche d'école et de garderie pour vos enfants.",
				"Marché immobilier, services d'achat et de vente, location et gestion immobilière.",
				"Conseils immobiliers.",
				"Organisation du déménagement.",
			],
			reviewName_1: "MARIA SMITH",
			reviewDescription_1:
				"'Cela fait 1 mois que je vis au Luxembourg grâce à Libling. J'ai trouvé un emploi dans le secteur de la technologie, là où je suis le plus spécialisé. Ils m'ont également aidé à ouvrir un compte bancaire, à faire la demande de permis de résidence et à me faire des amis au Luxembourg.'",
			reviewName_2: "LUIS MORENO",
			reviewDescription_2:
				"'Je m'appelle Luis Moreno et je viens du Pérou. Ma copine et moi avons décidé de partir au Luxembourg à la recherche d'un meilleur avenir pour nous deux il y a un an. Nous avons sollicité l'aide de Libling, et c'était certainement l'une des meilleures décisions que nous aurions pu prendre.'",
			reviewName_3: "LAURA MARTINEZ",
			reviewDescription_3:
				"'Bonjour, je m'appelle Laura et je viens du Mexique. Luxembourg a toujours été une ville magnifique avec de grandes opportunités pour moi, alors j'ai contacté Libling pour obtenir les requis nécessaires pour y vivre. Je les recommande à 100%.'",
		},
		services: {
			aditionalTitle_1: "Nous en avons plus pour vous",
			aditionalService_1: "Organisation de la prise en charge à l'aéroport",
			aditionalService_2:
				"Nous planifions et organisons votre voyage et déménagement au Luxembourg 🇱🇺",
			aditionalService_3:
				"Assistance dans les services de nettoyage et d'entretien",
			aditionalService_4:
				"Assistance de soutien après le déménagement (1 mois par téléphone).",
			sectionTitle_1: "Nous vous accompagnons dès le premier jour",
			sectionContent_1:
				"De votre arrivée à l'aéroport à une visite de la ville de Luxembourg, Libling sera là pour vous, vous fournissant toutes les informations dans votre langue maternelle.",
			sectionTitle_2: "Des forfaits pour tout le monde",
			cardTitle_1: "Basique",
			cardList_1: [
				"Assitance légère",
				"Procédures administratives - Inscription",
				"Inscription + 4 services",
				"1 jour d'assistance",
			],
			cardTitle_2: "Standard",
			cardList_2: [
				"Assistance standard",
				"Procédures administratives - Inscription + 4 services",
				"Recherche de maison + accompagnement",
				"Recherche d'école",
				"2 jours d'assistance",
			],
			cardTitle_3: "Premium",
			cardList_3: [
				"Assistance complète",
				"Procédures administratives - Inscription + 4 services",
				"Recherche de maison avec accompagnement tout au long du processus de recherche",
				"Recherche d'école / garderie",
				"Logement à court terme",
				"Organisation de la prise en charge à l'aéroport",
				"Visite d'orientation",
				"3 jours d'assistance",
			],
			cardTitle_4: "Liste des services et consultations supplémentaires",
			cardList_4: [
				"Nous disposons d'une équipe complète faisant partie de Libling Solutions et sommes à votre disposition :",
				"Conseil immobilier / logement",
				"Conseil en architecture / construction / investissement",
				"Conseil juridique",
				"Consultation médicale",
				"Vie sociale/événements sociaux et culturels",
				"Organisation et planification personnalisées de votre voyage et déménagement",
			],
			cardDescription_4: "Service d'orientation et de consultation basique",
			cardActionText: "Demander",
			sectionTitle_3: "L'éducation au Luxembourg est GRATUITE !",
			sectionContent_3:
				"L'éducation des tout-petits est d'une grande importance, et Libling vous aidera à trouver des écoles/collèges et des garderies qui conviennent à votre famille.",
			sectionTitle_4: "Nous vous aidons avec vos procédures administratives",
			sectionContent_4:
				"Lors de votre arrivée au Luxembourg, Libling aura tout à portée de main pour vous et votre famille. Cela comprend un logement temporaire, des services de transfert, un guide d'installation et une assistance téléphonique.",
			sectionTitle_5: "Planifiez votre rendez-vous",
			sectionContent_5:
				"Si vous souhaitez avoir une réunion avec nous, vous pouvez consulter notre calendrier pour vérifier notre disponibilité et ainsi offrir l'attention et le service que vous méritez.",
			sectionButton_5: "Prendre rendez-vous",
		},
		contact: {
			calendarTitle: "Sélectionnez une date",
			sectionTitle_1: "Planifiez avec nous !",
			sectionContent_1:
				"Vous souhaitez avoir une réunion avec Libling Solutions? Nous sommes à votre entière disposition pour vous fournir un service complet.",
			sectionTitle_2: "Nous te tiendrons toujours au courant de tout",
			sectionContent_2:
				"Parce que vous êtes notre priorité. Abonnez-vous à notre bulletin d'information pour être le premier à recevoir toutes nos nouveautés, actualités, produits et services.",
			form_name: "Noms",
			form_subject: "Objet",
			form_email: "E-mail",
			form_message: "Message",
			form_button: "Envoyer",
		},
		about: {
			titleHeader_1: "Nous partageons",
			titleHeader_2: "notre histoire",
			titleHeader_3: "avec vous",
			sectionTitle_1: "Qui sommes-nous ?",
			sectionContent_1:
				"Libling Solutions est la première entreprise hispano-américaine de relocalisation/déménagement et d'immobilier au Grand-Duché de Luxembourg. Elle a été fondée et est dirigée par Madame Lidiz Cruz, luxembourgeoise et hondurienne, Elle croit fermement qu'avec de l'informations et une excellente guidance, vous pouvez réussir votre déménagement et votre intégration au Luxemboug.",
			sectionTitle_2:
				"Innovateurs en relocalisation et immobilier au Grand-Duché",
			sectionContent_2:
				"Chez Libling Solutions, vous trouverez tout ce dont vous avez besoin. Nous croyons que la relocalisation doit être agréable et personnalisée, vous garantissant, à vous et à votre famille, un excellent processus de déménagement.",
			sectionTitle_3: "Notre objectif est votre bien-être",
			sectionContent_3:
				"Libling Solutions a pour objectif de vous soutenir, vous aider et tout faciliter pour que votre déménagement au Grand-Duché soit agréable et confortable. Nous avons une équipe de professionnels spécialisés dans chacun de vos besoins et dans votre langue. Notre priorité est de vous fournir un service de qualité.",
		},
		mail: {
			main: "J'aimerais avoir plus d'informations sur Libling",
			subject_1: "Information",
			subject_2: "Services",
			package: "Je suis intéressé par le pack suivant: ",
			date: "Bonjour, je souhaite un rendez-vous pour la journée :",
			notify: "Ton message a été envoyé avec succès",
			failed: "La demande n'a pas pu être complétée",
		},
	},
}
